#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
_phase4_contract.py - Phase 4 golden-dataset contract (scenario matrices,
tolerance-policy routes, and expected-divergence routes).

Phase 4 ("Tier-2 moderate functions and emissions") adds a SECOND,
separately manifested C++-oracle golden dataset alongside the frozen Phase 2
canonical dataset. It builds **no new harness mode**: every scenario below is
driven through one of the six already-qualified Phase 2 modes (``consume``,
``litter_eq``, ``shrub_herb_eq``, ``mortality``, ``bark_thick``,
``canopy_cover``), using those modes' existing, unchanged input schemas.

Why this lives in its own module rather than in ``_output_contract.py``:
``_output_contract.py`` is one of the seven files hashed into every Phase 2
manifest's ``generator_source_sha256``. Editing it would make the committed
Phase 2 manifests' recorded generator digests disagree with the files on
disk. Keeping the Phase 4 registry in a new module limits that unavoidable
disturbance to the two files Phase 4 genuinely must change
(``_golden_manifest.py``, which owns the dataset-aware manifest contract, and
``tolerance_policy.json``, which owns the per-output evidence records).

Scenario-matrix design rule (from the approved plan): equivalence partitions,
thresholds, and distinct equation-routing branches - never an indiscriminate
Cartesian product. Every scenario below names the
``gate0/07-branch-traceability.csv`` branch ID(s) it is intended to exercise.

Tolerance-policy namespace: Phase 4 entries live in their own ``<mode>_p4``
sections of ``tolerance_policy.json``. This keeps the frozen Phase 2 canonical
key sets (which the committed Phase 2 manifests cite verbatim) byte-stable
while still using one shared policy file and one shared per-key evidence
schema.

Function order: module constants first, then top-level functions alphabetized
private-then-public, per AGENTS.md.
"""
from __future__ import annotations

import csv
import json
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

from tests._support import PROJECT_ROOT, TEST_GOLDEN_DIR
from tests.cpp_parity_live._golden_manifest import (
    load_tolerance_policy,
    MODE_OUTPUT_SUFFIXES as _MODE_OUTPUT_SUFFIXES,
)
from tests.cpp_parity_live.test_cpp_harness_contract import MODES

#: Root of the Phase 4 golden tree. Sibling of ``phase2/``; never merged with
#: it, never regenerated by the Phase 2 generator.
GOLDEN_ROOT: str = os.path.join(TEST_GOLDEN_DIR, "phase4")

#: Dataset identifier stamped into every Phase 4 manifest's ``dataset`` field
#: (Phase 2 manifests carry no such field and default to ``"phase2"``).
DATASET_NAME: str = "phase4"

#: The Phase 4 modes, in generation order. The same six qualified Phase 2
#: modes - Phase 4 adds no harness mode (plan: "Phase 4 builds no harness
#: mode at all").
PHASE4_MODES: Tuple[str, ...] = (
    "consume", "litter_eq", "shrub_herb_eq", "mortality", "bark_thick",
    "canopy_cover",
)


# ===========================================================================
# consume scenarios
#
# Driven through the full, faithful CM_Mngr -> BCM_Mngr -> Burnup pipeline
# (fof_cm.cpp:42). Every row starts from the Phase 2 canonical all-ok row and
# overrides only the fields the scenario is about, so an unintended input
# difference cannot masquerade as a routing difference.
# ===========================================================================

#: Column-name -> index for the 49-column consume input schema, derived from
#: the harness's own header constant rather than re-listed here.
CONSUME_INDEX: Dict[str, int] = {
    name: i for i, name in enumerate(MODES["consume"]["header"])
}

#: ``(case_id, {column: value}, "branch ids exercised")`` per consume
#: scenario. ``case_id``s are stable, human-readable and unique.
CONSUME_SCENARIOS: Tuple[Tuple[str, Dict[str, str], str], ...] = (
    # --- InteriorWest / PacificWest duff-percent + MSE routing ---
    ("iw-nat-entire-m050", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50",
    }, "BR-DUF-IW; BR-MSE-10"),
    ("iw-nat-entire-m130", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "130",
    }, "BR-DUF-IW; BR-MSE-10"),
    ("iw-nat-lower-m050", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Lower",
        "duff_moist_pct": "50",
    }, "BR-DUF-IW; BR-MSE-13"),
    ("iw-nat-lower-m180", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Lower",
        "duff_moist_pct": "180",
    }, "BR-DUF-IW; BR-MSE-13"),
    ("iw-slash-lower-m050", {
        "region": "InteriorWest", "fuel_cat": "Slash", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Lower",
        "duff_moist_pct": "50",
    }, "BR-DUF-IW; BR-MSE-9"),
    ("iw-slash-lower-m150", {
        "region": "InteriorWest", "fuel_cat": "Slash", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Lower",
        "duff_moist_pct": "150",
    }, "BR-DUF-IW; BR-MSE-9"),
    ("iw-slash-nfdr-m020", {
        "region": "InteriorWest", "fuel_cat": "Slash", "cover_group": "",
        "cover_class": "", "duff_moist_method": "NFDR",
        "duff_moist_pct": "20", "dw1000_moist_pct": "20",
    }, "BR-DUF-IW; BR-MSE-11"),
    ("iw-nat-nfdr-m020", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "NFDR",
        "duff_moist_pct": "20", "dw1000_moist_pct": "20",
    }, "BR-DUF-IW; BR-MSE-12"),
    ("iw-slash-adjnfdr-m028", {
        "region": "InteriorWest", "fuel_cat": "Slash", "cover_group": "",
        "cover_class": "", "duff_moist_method": "AdjNFDR",
        "duff_moist_pct": "28", "dw1000_moist_pct": "28",
    }, "BR-MSE-11 (Adj-NFDR path, F-27a)"),
    ("iw-pn-lower-m050", {
        "region": "InteriorWest", "fuel_cat": "Natural",
        "cover_group": "Ponderosa", "cover_class": "",
        "duff_moist_method": "Lower", "duff_moist_pct": "50",
    }, "BR-DUF-IW (Ponderosa Eq 4)"),
    ("iw-pn-entire-m050", {
        "region": "InteriorWest", "fuel_cat": "Natural",
        "cover_group": "Ponderosa", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
    }, "BR-DUF-IW (Ponderosa Eq 2)"),
    ("pw-nat-entire-m050", {
        "region": "PacificWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50",
    }, "BR-DUF-PW; BR-MSE-10"),

    # --- NorthEast (F-23 case-6 reproduction and cover-group routes) ---
    ("ne-gen-entire-m020", {
        "region": "NorthEast", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "20",
    }, "BR-DUF-NE-GEN; BR-DUF-DEPTH-OVERRIDE (F-23)"),
    ("ne-rjp-entire-m020", {
        "region": "NorthEast", "fuel_cat": "Natural",
        "cover_group": "RedJacPin", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "20",
    }, "BR-DUF-NE-RJP-E"),
    ("ne-rjp-lower-m050", {
        "region": "NorthEast", "fuel_cat": "Natural",
        "cover_group": "RedJacPin", "cover_class": "",
        "duff_moist_method": "Lower", "duff_moist_pct": "50",
    }, "BR-DUF-NE-RJP-L"),
    ("ne-bbs-lower-m050", {
        "region": "NorthEast", "fuel_cat": "Natural",
        "cover_group": "BalBRWSpr", "cover_class": "",
        "duff_moist_method": "Lower", "duff_moist_pct": "50",
    }, "BR-DUF-NE-BAL-L"),
    ("ne-bbs-entire-m050", {
        "region": "NorthEast", "fuel_cat": "Natural",
        "cover_group": "BalBRWSpr", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
    }, "BR-DUF-NE-BAL-E"),
    ("ne-wph-entire-m050", {
        "region": "NorthEast", "fuel_cat": "Natural",
        "cover_group": "WhiPinHem", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
    }, "BR-DUF-NE-WPH"),

    # --- SouthEast, Pocosin, Chaparral, Coastal Plain, Piles ---
    ("se-gen-entire-m050", {
        "region": "SouthEast", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50",
    }, "BR-DUF-SE; BR-HRB-222; BR-SHR-234"),
    ("se-poc-entire-m050", {
        "region": "SouthEast", "fuel_cat": "Natural",
        "cover_group": "Pocosin", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
    }, "BR-DUF-POCO; BR-MSE-202"),
    ("chaparral-entire-m050", {
        "region": "InteriorWest", "fuel_cat": "Natural",
        "cover_group": "ShrubGroupChaparral", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
    }, "BR-DUF-CHAP"),
    ("se-cp-entire-m050", {
        "region": "SouthEast", "fuel_cat": "Natural",
        "cover_group": "CoastPlain", "cover_class": "",
        "duff_moist_method": "Entire", "duff_moist_pct": "50",
        "litter_moist_pct": "25",
    }, "BR-DUF-CP; BR-LIT-CP"),
    ("piles-entire-m050", {
        "region": "InteriorWest", "fuel_cat": "Piles", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50",
    }, "BR-DUF-PILE; BR-MSE-PILE"),

    # --- boundary / zero-load cases ---
    # duff_moist == 10 is the LOWEST value CM_Mngr's own input validation
    # accepts ("Duff Moisture 5.00 is out limits ( 10.00 -> 197.20)",
    # reproduced directly against the compiled harness), so 10 is the only
    # input that can reach DUF_Mngr's `f_MoistDuff <= 10.0 -> 100 percent`
    # rule (fof_duf.cpp:366-369) through the real pipeline.
    ("iw-nat-entire-m010", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "10",
    }, "BR-DUF-IW (duff_moist <= 10 -> 100 pct rule, at the boundary)"),
    ("iw-nat-entire-zero-duff", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "duff_tac": "0", "duff_depth_in": "0",
    }, "BR-DUF-IW; BR-MSE-10 (zero duff load)"),

    # --- crown foliage/branch consumption boundaries ---
    ("iw-crown-burn-000", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "pct_crown_burn": "0",
    }, "BR-CAN-37; BR-CAN-38 (zero crown burn)"),
    ("iw-crown-burn-100", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "pct_crown_burn": "100",
    }, "BR-CAN-37; BR-CAN-38 (full crown burn)"),
    ("iw-crown-zero-load", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "crown_fol_tac": "0", "crown_bra_tac": "0",
        "pct_crown_burn": "50",
    }, "BR-CAN-37; BR-CAN-38 (zero crown load)"),

    # --- emissions: the legacy (ES_Calc) dispatch path ---
    # critical_intensity_kw_m < 0 selects ES_Calc (bur_brn.cpp:320,332).
    # The three ef_* group columns are still loaded through
    # NES_Read/NES_Get_MajFactor for reproducibility; ES_Calc ignores them.
    ("emis-legacy-iw", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "critical_intensity_kw_m": "-1",
    }, "BR-EMI-LEGACY"),
    ("emis-legacy-se", {
        "region": "SouthEast", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "critical_intensity_kw_m": "-1",
    }, "BR-EMI-LEGACY"),

    # --- emissions: the expanded (ES_Calc_NEW) dispatch path, with factor
    #     group configurations distinct from the Phase 2 canonical row ---
    ("emis-expanded-g258", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "critical_intensity_kw_m": "50",
        "ef_flame_group": "2", "ef_smolder_group": "5", "ef_duff_group": "8",
    }, "BR-EMI-EXPANDED"),
    ("emis-expanded-g378", {
        "region": "InteriorWest", "fuel_cat": "Natural", "cover_group": "",
        "cover_class": "", "duff_moist_method": "Entire",
        "duff_moist_pct": "50", "critical_intensity_kw_m": "50",
        "ef_flame_group": "3", "ef_smolder_group": "7", "ef_duff_group": "8",
    }, "BR-EMI-EXPANDED"),
)


# ===========================================================================
# litter_eq scenarios (direct PFW_Litter_Eq997 / LitterSouthEast calls)
# ===========================================================================

#: ``(case_id, equ, load_tac, dw10_moist_pct, branch ids)``. ``equ=998``
#: takes no moisture, so its moisture column must be the NA sentinel.
LITTER_EQ_SCENARIOS: Tuple[Tuple[str, str, str, str, str], ...] = (
    ("lit997-l025-m05", "997", "0.25", "5", "BR-LIT-997"),
    ("lit997-l025-m20", "997", "0.25", "20", "BR-LIT-997"),
    ("lit997-l025-m60", "997", "0.25", "60", "BR-LIT-997"),
    ("lit997-l100-m05", "997", "1.0", "5", "BR-LIT-997"),
    ("lit997-l200-m20", "997", "2.0", "20", "BR-LIT-997"),
    ("lit997-l500-m60", "997", "5.0", "60", "BR-LIT-997"),
    ("lit997-l1000-m60", "997", "10.0", "60", "BR-LIT-997"),
    ("lit997-l000-m20", "997", "0.0", "20", "BR-LIT-997 (zero load)"),
    ("lit998-l000", "998", "0.0", "NA", "BR-LIT-998 (zero load)"),
    ("lit998-l050", "998", "0.5", "NA", "BR-LIT-998"),
    ("lit998-l200", "998", "2.0", "NA", "BR-LIT-998"),
    ("lit998-l1000", "998", "10.0", "NA", "BR-LIT-998"),
)


# ===========================================================================
# shrub_herb_eq scenarios (direct Calc_Shrub / Calc_Herb /
# Calc_CrownFoliage / Calc_CrownBranch calls)
# ===========================================================================

#: Column-name -> index for the 15-column shrub_herb_eq input schema.
SHRUB_HERB_INDEX: Dict[str, int] = {
    name: i for i, name in enumerate(MODES["shrub_herb_eq"]["header"])
}

#: ``(case_id, {column: value}, branch ids)``. Every row emits shrub, herb,
#: crown-foliage and crown-branch results, so a single row covers one routing
#: branch in each of the four equation families at once.
SHRUB_HERB_EQ_SCENARIOS: Tuple[Tuple[str, Dict[str, str], str], ...] = (
    ("shr23-herb22-iw", {
        "region": "InteriorWest", "cover_group": "", "season": "Summer",
    }, "BR-SHR-23; BR-HRB-22"),
    ("shr231-herb22-iw-sg", {
        "region": "InteriorWest", "cover_group": "ShrubGroup",
        "season": "Summer",
    }, "BR-SHR-231; BR-HRB-22"),
    ("shr232-herb22-iw-sb-summer", {
        "region": "InteriorWest", "cover_group": "Sagebrush",
        "season": "Summer",
    }, "BR-SHR-232; BR-HRB-22"),
    ("shr233-herb22-iw-sb-fall", {
        "region": "InteriorWest", "cover_group": "Sagebrush",
        "season": "Fall",
    }, "BR-SHR-233A; BR-HRB-22"),
    ("shr23-herb221-iw-gg-spring", {
        "region": "InteriorWest", "cover_group": "GrassGroup",
        "season": "Spring",
    }, "BR-SHR-23; BR-HRB-221"),
    ("shr23-herb22-iw-gg-summer", {
        "region": "InteriorWest", "cover_group": "GrassGroup",
        "season": "Summer",
    }, "BR-SHR-23; BR-HRB-22"),
    ("shr234-herb222-se", {
        "region": "SouthEast", "cover_group": "", "season": "Summer",
    }, "BR-SHR-234; BR-HRB-222"),
    ("shr234-herb222-se-highlit", {
        "region": "SouthEast", "cover_group": "", "season": "Summer",
        "litter_tac": "8.0", "herb_tac": "0.2",
    }, "BR-SHR-234; BR-HRB-222 (C++ [0, herb] clamp, F-12)"),
    # Eq 222 = -0.059 + 0.004*Lit + 0.917*Herb goes NEGATIVE for a small herb
    # load with no litter, so C++'s `if (*af_Con < 0) *af_Con = 0` clamp
    # (fof_hsf.cpp:322-323) actually fires here.
    ("herb222-se-clamp-low", {
        "region": "SouthEast", "cover_group": "", "season": "Summer",
        "litter_tac": "0.0", "herb_tac": "0.05",
    }, "BR-HRB-222 (C++ lower clamp to 0, F-12)"),
    # ... and EXCEEDS the pre-fire herb load for a large litter load, so
    # C++'s `if (*af_Con > f_Herb) *af_Con = f_Herb` clamp (fof_hsf.cpp:
    # 320-321) fires instead.
    ("herb222-se-clamp-high", {
        "region": "SouthEast", "cover_group": "", "season": "Summer",
        "litter_tac": "20.0", "herb_tac": "0.1",
    }, "BR-HRB-222 (C++ upper clamp to herb load, F-12)"),
    ("shr233-herb222-se-poc-spring", {
        "region": "SouthEast", "cover_group": "Pocosin", "season": "Spring",
    }, "BR-SHR-233B; BR-HRB-222"),
    ("shr235-herb222-se-poc-summer", {
        "region": "SouthEast", "cover_group": "Pocosin", "season": "Summer",
    }, "BR-SHR-235; BR-HRB-222"),
    ("shr236-herb223-se-pfw-summer", {
        "region": "SouthEast", "cover_group": "PinFlaWoo", "season": "Summer",
    }, "BR-SHR-236; BR-HRB-223"),
    ("shr236-herb223-se-pfw-fall", {
        "region": "SouthEast", "cover_group": "PinFlaWoo", "season": "Fall",
    }, "BR-SHR-236; BR-HRB-223 (season flag 0)"),
    ("crown-burn-000", {
        "region": "InteriorWest", "cover_group": "", "season": "Summer",
        "pct_crown_burn": "0",
    }, "BR-CAN-37; BR-CAN-38 (zero crown burn)"),
    ("crown-burn-100", {
        "region": "InteriorWest", "cover_group": "", "season": "Summer",
        "pct_crown_burn": "100",
    }, "BR-CAN-37; BR-CAN-38 (full crown burn)"),
    ("zero-shrub-herb-crown", {
        "region": "InteriorWest", "cover_group": "", "season": "Summer",
        "shrub_tac": "0", "herb_tac": "0", "crown_fol_tac": "0",
        "crown_bra_tac": "0",
    }, "BR-SHR-23; BR-HRB-22; BR-CAN-37; BR-CAN-38 (zero loads)"),
)


# ===========================================================================
# mortality scenarios
#
# Species codes are real, tracked FOF_SPP.CSV codes (the file the harness
# loads via MRT_LoadSpe()); each was chosen because that species' `Mort`
# column in that file selects exactly the equation named in the comment.
# ===========================================================================

#: Column-name -> index for the 14-column mortality input schema.
MORTALITY_INDEX: Dict[str, int] = {
    name: i for i, name in enumerate(MODES["mortality"]["header"])
}

#: ``(case_id, {column: value}, branch ids)``.
MORTALITY_SCENARIOS: Tuple[Tuple[str, Dict[str, str], str], ...] = (
    # --- BolCha (BC_Calc), one representative species per sr_BCT equation ---
    ("bc100-acru", {
        "species": "ACRU", "equ_type": "BolCha", "dbh_in": "12",
        "bole_char_ft": "4",
    }, "BR-MRT-BC-100"),
    ("bc100-acru-small", {
        "species": "ACRU", "equ_type": "BolCha", "dbh_in": "2",
        "bole_char_ft": "1",
    }, "BR-MRT-BC-100"),
    ("bc101-cofl2", {
        "species": "COFL2", "equ_type": "BolCha", "dbh_in": "6",
        "bole_char_ft": "2",
    }, "BR-MRT-BC-101"),
    ("bc102-nysy", {
        "species": "NYSY", "equ_type": "BolCha", "dbh_in": "10",
        "bole_char_ft": "3",
    }, "BR-MRT-BC-102"),
    ("bc103-oxar", {
        "species": "OXAR", "equ_type": "BolCha", "dbh_in": "8",
        "bole_char_ft": "3",
    }, "BR-MRT-BC-103"),
    ("bc104-qual", {
        "species": "QUAL", "equ_type": "BolCha", "dbh_in": "14",
        "bole_char_ft": "5",
    }, "BR-MRT-BC-104"),
    ("bc105-quco2", {
        "species": "QUCO2", "equ_type": "BolCha", "dbh_in": "14",
        "bole_char_ft": "5",
    }, "BR-MRT-BC-105"),
    ("bc106-quma3", {
        "species": "QUMA3", "equ_type": "BolCha", "dbh_in": "9",
        "bole_char_ft": "3",
    }, "BR-MRT-BC-106"),
    ("bc107-qumo4", {
        "species": "QUMO4", "equ_type": "BolCha", "dbh_in": "14",
        "bole_char_ft": "5",
    }, "BR-MRT-BC-107"),
    ("bc108-quve", {
        "species": "QUVE", "equ_type": "BolCha", "dbh_in": "11",
        "bole_char_ft": "4",
    }, "BR-MRT-BC-108"),
    ("bc109-saal5", {
        "species": "SAAL5", "equ_type": "BolCha", "dbh_in": "5",
        "bole_char_ft": "2",
    }, "BR-MRT-BC-109"),
    ("bc-zero-char-qual", {
        "species": "QUAL", "equ_type": "BolCha", "dbh_in": "14",
        "bole_char_ft": "0",
    }, "BR-MRT-BC-104 (zero bole char)"),

    # --- CroSco (MRT_Calc), one representative species per switch case ---
    ("cs01-abam-dbh12", {
        "species": "ABAM", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "20",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-01"),
    ("cs01-abam-dbh1", {
        "species": "ABAM", "equ_type": "CroSco", "dbh_in": "1",
        "ht_ft": "20", "crown_ratio_x10": "50", "fs_value_ft": "8",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-01 (DBH == 1 boundary)"),
    ("cs01-abam-dbh09", {
        "species": "ABAM", "equ_type": "CroSco", "dbh_in": "0.9",
        "ht_ft": "20", "crown_ratio_x10": "50", "fs_value_ft": "8",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-01 (DBH < 1, small-tree fallback)"),
    ("cs03-piab-dbh12", {
        "species": "PIAB", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "20",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-03"),
    ("cs03-piab-dbh1", {
        "species": "PIAB", "equ_type": "CroSco", "dbh_in": "1",
        "ht_ft": "20", "crown_ratio_x10": "50", "fs_value_ft": "8",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-03 (DBH == 1 boundary vs case 1)"),
    ("cs03-piab-dbh11", {
        "species": "PIAB", "equ_type": "CroSco", "dbh_in": "1.1",
        "ht_ft": "20", "crown_ratio_x10": "50", "fs_value_ft": "8",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-03 (DBH > 1 boundary vs case 1)"),
    # Case 3's 0.8 floor (fof_mrt.cpp:391-392), which the three scenarios
    # above never reach because each of their probabilities is already
    # above 0.99. A large tree (DBH 12 > 1, so the large-tree branch) whose
    # crown the fire never reaches: with crown_ratio_x10 = 3 the crown
    # occupies the top 30 % of a 40 ft tree, so its base is at 28 ft, and a
    # 0 ft scorch height gives f_B <= 0 -> f_B = 0 -> f_CK = f_CSL = 0
    # (fof_mrt.cpp:314-327). The equation's crown term therefore vanishes,
    # the raw probability falls below 0.8, and the floor clamps it. The
    # expected value is EXACTLY 0.800000 in the golden - the clamp, not an
    # approximation of it.
    ("cs03-piab-floor08", {
        "species": "PIAB", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "40", "crown_ratio_x10": "3", "fs_value_ft": "0",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-03 (0.8 floor)"),
    ("cs04-potr5-lowsev", {
        "species": "POTR5", "equ_type": "CroSco", "dbh_in": "10",
        "ht_ft": "50", "crown_ratio_x10": "40", "fs_value_ft": "6",
        "fs_kind": "Flame", "fire_severity": "Low",
    }, "BR-MRT-CS-04"),
    ("cs04-potr5-highsev", {
        "species": "POTR5", "equ_type": "CroSco", "dbh_in": "10",
        "ht_ft": "50", "crown_ratio_x10": "40", "fs_value_ft": "6",
        "fs_kind": "Flame", "fire_severity": "High",
    }, "BR-MRT-CS-04"),
    ("cs05-pipa2", {
        "species": "PIPA2", "equ_type": "CroSco", "dbh_in": "10",
        "ht_ft": "50", "crown_ratio_x10": "40", "fs_value_ft": "20",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-05"),
    ("cs10-abco", {
        "species": "ABCO", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-10"),
    ("cs11-abgr", {
        "species": "ABGR", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-11"),
    ("cs12-cade27", {
        "species": "CADE27", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-12"),
    ("cs14-laoc", {
        "species": "LAOC", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-14"),
    ("cs15-pien", {
        "species": "PIEN", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-15"),
    ("cs16-abma", {
        "species": "ABMA", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-16"),
    ("cs17-pial", {
        "species": "PIAL", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-17"),
    ("cs18-pila", {
        "species": "PILA", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-18"),
    ("cs19-pije", {
        "species": "PIJE", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-19"),
    ("cs20-psme", {
        "species": "PSME", "equ_type": "CroSco", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "50", "fs_value_ft": "25",
        "fs_kind": "Scorch",
    }, "BR-MRT-CS-20"),
    ("cs21-pipobh-seedling", {
        "species": "PIPO_BH", "equ_type": "CroSco", "dbh_in": "0.5",
        "ht_ft": "3", "crown_ratio_x10": "60", "fs_value_ft": "2",
        "fs_kind": "Flame",
    }, "BR-MRT-CS-21 (seedling class)"),
    ("cs21-pipobh-sapling", {
        "species": "PIPO_BH", "equ_type": "CroSco", "dbh_in": "2",
        "ht_ft": "12", "crown_ratio_x10": "60", "fs_value_ft": "4",
        "fs_kind": "Flame",
    }, "BR-MRT-CS-21 (sapling class)"),
    ("cs21-pipobh-large", {
        "species": "PIPO_BH", "equ_type": "CroSco", "dbh_in": "14",
        "ht_ft": "70", "crown_ratio_x10": "50", "fs_value_ft": "10",
        "fs_kind": "Flame",
    }, "BR-MRT-CS-21 (large class)"),

    # --- CroDam (PFI_Calc), one representative species per sr_EFR equation.
    #
    # `ckr_rating` fills d_MIS.f_CKR, which C++ documents as the cambium kill
    # RATING 0-4 (fof_mrt.cpp:1937 "a_MIS->f_CKR....cambium kill ratio 0-4")
    # and validates as 0-4 (fof_mrt.cpp:1849-1851), not as a percent. Schema
    # v1 named the column `ckr_pct`, a misnomer; schema v2 renamed it.
    # `cvk_pct` fills d_MIS.f_CrnDam, the crown-damage percent every PFI
    # equation reads directly.
    #
    # `density_tpa` (schema v2) fills d_MIS.f_Den. ValidInput requires
    # 1 <= f_Den <= 20000 (fof_mrt.cpp:1854-1856) on every CroDam row, so
    # without it PFI_Calc rejected every row before reaching an equation
    # (F-45). The value itself does not enter any PFI equation - it is
    # consumed only by MRT_Total's stand accumulators (fof_mrt.cpp:818-875),
    # which this mode does not emit - so 100 tpa is a valid, inert choice
    # and the boundary rows below carry the interesting values instead.
    #
    # Python's mort_crcabe does NOT take crown damage directly: it derives
    # BOTH `cvs` and `cls` from scorch height / height / crown depth and then
    # uses one or the other per equation. The two contracts therefore
    # coincide only where cvs == cls == f_CrnDam, which holds exactly at 0 %
    # and 100 % crown scorch. Both endpoints are generated for every
    # equation so the comparison is real rather than approximate.
    ("cd-wf-abco", {
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-WF (full crown damage)"),
    ("cd-wf-abco-cvk0", {
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-WF (zero crown damage)"),
    ("cd-sf-abgr", {
        "species": "ABGR", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-SF (full crown damage)"),
    ("cd-sf-abgr-cvk0", {
        "species": "ABGR", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-SF (zero crown damage)"),
    ("cd-wl-laoc", {
        "species": "LAOC", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-WL (full crown damage)"),
    ("cd-wl-laoc-cvk0", {
        "species": "LAOC", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-WL (zero crown damage)"),
    ("cd-ic-cade27", {
        "species": "CADE27", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-IC (full crown damage)"),
    ("cd-ic-cade27-cvk0", {
        "species": "CADE27", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-IC (zero crown damage)"),
    ("cd-wp-pial", {
        "species": "PIAL", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-WP (full crown damage)"),
    ("cd-wp-pial-cvk0", {
        "species": "PIAL", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-WP (zero crown damage)"),
    ("cd-es-pien", {
        "species": "PIEN", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-ES (full crown damage)"),
    ("cd-es-pien-cvk0", {
        "species": "PIEN", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-ES (zero crown damage)"),
    ("cd-rf-abma", {
        "species": "ABMA", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-RF (full crown damage)"),
    ("cd-rf-abma-cvk0", {
        "species": "ABMA", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-RF (zero crown damage)"),
    ("cd-sp-pila", {
        "species": "PILA", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "beetles": "1",
        "density_tpa": "100",
    }, "BR-MRT-CD-SP (full crown damage)"),
    ("cd-sp-pila-cvk0", {
        "species": "PILA", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "beetles": "1",
        "density_tpa": "100",
    }, "BR-MRT-CD-SP (zero crown damage)"),
    ("cd-pp-pije", {
        "species": "PIJE", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-PP (full crown damage)"),
    ("cd-pp-pije-cvk0", {
        "species": "PIJE", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-PP (zero crown damage)"),
    ("cd-pk-pijek", {
        "species": "PIJEK", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-PK (full crown damage)"),
    ("cd-pk-pijek-cvk0", {
        "species": "PIJEK", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-PK (zero crown damage)"),
    ("cd-df-psme", {
        "species": "PSME", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "beetles": "1",
        "density_tpa": "100",
    }, "BR-MRT-CD-DF (full crown damage)"),
    ("cd-df-psme-cvk0", {
        "species": "PSME", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "0",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "0",
        "beetles": "1",
        "density_tpa": "100",
    }, "BR-MRT-CD-DF (zero crown damage)"),
    ("cd-df-psme-nobeetle", {
        "species": "PSME", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "beetles": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-DF (beetles off)"),
    ("cd-sp-pila-nobeetle", {
        "species": "PILA", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "beetles": "0",
        "density_tpa": "100",
    }, "BR-MRT-CD-SP (beetles off)"),
    ("cd-wf-abco-ckr0", {
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "0", "cvk_pct": "100",
        "density_tpa": "100",
    }, "BR-MRT-CD-WF (zero cambium kill rating)"),

    # --- ValidInput density boundaries (BR-MRT-CD-VAL).
    #
    # ValidInput's test is `f_Den < 1.0 || f_Den > 20000`
    # (fof_mrt.cpp:1854-1856), so 1 and 20000 are the inclusive valid
    # boundaries and 0 / 20001 are the first invalid values on each side.
    # The two rejections carry expect_error=1, so the harness's two-sided
    # rule requires the error to actually be observed; a silently
    # successful row would be an `unexpected_failure` and a nonzero exit.
    ("cd-density-min", {
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "1",
    }, "BR-MRT-CD-VAL (density lower bound, valid)"),
    ("cd-density-max", {
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "20000",
    }, "BR-MRT-CD-VAL (density upper bound, valid)"),
    ("cd-density-zero", {
        "expect_error": "1",
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "0",
    }, "BR-MRT-CD-VAL (density below lower bound, rejected)"),
    ("cd-density-over", {
        "expect_error": "1",
        "species": "ABCO", "equ_type": "CroDam", "dbh_in": "12",
        "ht_ft": "60", "crown_ratio_x10": "10", "fs_value_ft": "60",
        "fs_kind": "Scorch", "ckr_rating": "3", "cvk_pct": "100",
        "density_tpa": "20001",
    }, "BR-MRT-CD-VAL (density above upper bound, rejected)"),
)


# ===========================================================================
# bark_thick scenarios (direct SMT_CalcBarkThick calls)
# ===========================================================================

#: ``(case_id, species, dbh_in, expect_error, branch ids)``. The species set
#: spans the low, middle and high ends of the 39-factor ladder plus the
#: single ``i_BrkEqu == 100`` (zero-bark) species and one deliberately
#: unknown species that must produce the C++ ``-1`` error return.
BARK_THICK_SCENARIOS: Tuple[Tuple[str, str, str, str, str], ...] = (
    ("brk01-alrh2-d12", "ALRH2", "12", "0", "BR-BRK-ALL (i_BrkEqu 1)"),
    ("brk07-acru-d12", "ACRU", "12", "0", "BR-BRK-ALL (i_BrkEqu 7)"),
    ("brk10-abba-d12", "ABBA", "12", "0", "BR-BRK-ALL (i_BrkEqu 10)"),
    ("brk19-acsp2-d12", "ACSP2", "12", "0", "BR-BRK-ALL (i_BrkEqu 19)"),
    ("brk20-abla-d12", "ABLA", "12", "0", "BR-BRK-ALL (i_BrkEqu 20)"),
    ("brk27-abco-d12", "ABCO", "12", "0", "BR-BRK-ALL (i_BrkEqu 27)"),
    ("brk30-abispp-d12", "ABISPP", "12", "0", "BR-BRK-ALL (i_BrkEqu 30)"),
    ("brk36-abmam-d12", "ABMAM", "12", "0", "BR-BRK-ALL (i_BrkEqu 36)"),
    ("brk38-pila-d12", "PILA", "12", "0", "BR-BRK-ALL (i_BrkEqu 38)"),
    ("brk39-chla-d12", "CHLA", "12", "0", "BR-BRK-ALL (i_BrkEqu 39)"),
    ("brk100-pipa2-d12", "PIPA2", "12", "0", "BR-BRK-ALL (i_BrkEqu 100 -> 0)"),
    ("brk16-cacol3-d0", "CACOL3", "0", "0", "BR-BRK-ALL (zero DBH)"),
    ("brk16-cacol3-d40", "CACOL3", "40", "0", "BR-BRK-ALL (large DBH)"),
    ("brk-unknown-species", "ZZZZ", "12", "1",
     "BR-BRK-ALL (unknown species -> C++ -1)"),
    # --- CROSS-REFERENCE ROWS -------------------------------------------
    # mort_crnsch's `bark_thickness` argument must come from a REAL,
    # manifested C++ oracle value, never an invented number (F-19 makes
    # Python's own calc_bark_thickness unusable). Each row below supplies
    # SMT_CalcBarkThick for exactly one (species, DBH) pair used by a
    # `mortality` CroSco scenario, so the mortality comparison is sourced
    # end-to-end from this same manifested dataset.
    ("brkxr-abam-d12", "ABAM", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-01"),
    ("brkxr-abam-d1", "ABAM", "1", "0", "BR-BRK-ALL; cross-ref MRT-CS-01"),
    ("brkxr-abam-d09", "ABAM", "0.9", "0", "BR-BRK-ALL; cross-ref MRT-CS-01"),
    ("brkxr-piab-d12", "PIAB", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-03"),
    ("brkxr-piab-d1", "PIAB", "1", "0", "BR-BRK-ALL; cross-ref MRT-CS-03"),
    ("brkxr-piab-d11", "PIAB", "1.1", "0", "BR-BRK-ALL; cross-ref MRT-CS-03"),
    ("brkxr-potr5-d10", "POTR5", "10", "0", "BR-BRK-ALL; cross-ref MRT-CS-04"),
    ("brkxr-pipa2-d10", "PIPA2", "10", "0", "BR-BRK-ALL; cross-ref MRT-CS-05"),
    ("brkxr-abco-d12", "ABCO", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-10"),
    ("brkxr-abgr-d12", "ABGR", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-11"),
    ("brkxr-cade27-d12", "CADE27", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-12"),
    ("brkxr-laoc-d12", "LAOC", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-14"),
    ("brkxr-pien-d12", "PIEN", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-15"),
    ("brkxr-abma-d12", "ABMA", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-16"),
    ("brkxr-pial-d12", "PIAL", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-17"),
    ("brkxr-pila-d12", "PILA", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-18"),
    ("brkxr-pije-d12", "PIJE", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-19"),
    ("brkxr-psme-d12", "PSME", "12", "0", "BR-BRK-ALL; cross-ref MRT-CS-20"),
    ("brkxr-pipobh-d05", "PIPO_BH", "0.5", "0", "BR-BRK-ALL; cross-ref MRT-CS-21"),
    ("brkxr-pipobh-d2", "PIPO_BH", "2", "0", "BR-BRK-ALL; cross-ref MRT-CS-21"),
    ("brkxr-pipobh-d14", "PIPO_BH", "14", "0", "BR-BRK-ALL; cross-ref MRT-CS-21"),
)

#: ``mortality`` CroSco case_id -> the ``bark_thick`` case_id supplying that
#: scenario's bark thickness. Every mortality-vs-Python comparison that needs
#: a bark thickness reads it from THIS manifested oracle row, never from a
#: hardcoded constant and never from Python's own (F-19-broken)
#: ``calc_bark_thickness``.
CROSCO_BARK_SOURCE: Dict[str, str] = {
    "cs01-abam-dbh12": "brkxr-abam-d12",
    "cs01-abam-dbh1": "brkxr-abam-d1",
    "cs01-abam-dbh09": "brkxr-abam-d09",
    "cs03-piab-dbh12": "brkxr-piab-d12",
    "cs03-piab-dbh1": "brkxr-piab-d1",
    "cs03-piab-dbh11": "brkxr-piab-d11",
    "cs03-piab-floor08": "brkxr-piab-d12",
    "cs04-potr5-lowsev": "brkxr-potr5-d10",
    "cs04-potr5-highsev": "brkxr-potr5-d10",
    "cs05-pipa2": "brkxr-pipa2-d10",
    "cs10-abco": "brkxr-abco-d12",
    "cs11-abgr": "brkxr-abgr-d12",
    "cs12-cade27": "brkxr-cade27-d12",
    "cs14-laoc": "brkxr-laoc-d12",
    "cs15-pien": "brkxr-pien-d12",
    "cs16-abma": "brkxr-abma-d12",
    "cs17-pial": "brkxr-pial-d12",
    "cs18-pila": "brkxr-pila-d12",
    "cs19-pije": "brkxr-pije-d12",
    "cs20-psme": "brkxr-psme-d12",
    "cs21-pipobh-seedling": "brkxr-pipobh-d05",
    "cs21-pipobh-sapling": "brkxr-pipobh-d2",
    "cs21-pipobh-large": "brkxr-pipobh-d14",
}


# ===========================================================================
# canopy_cover scenarios (SMT_CalcCrnCov per tree + MRT_Overlap per stand)
# ===========================================================================

#: ``(case_id, stand_id, species, dbh_in, ht_ft, expect_error, branch ids)``.
#: Rows for one stand MUST be contiguous - the harness enforces this
#: (test_harness.cpp's stand-contiguity check) and rejects interleaving.
CANOPY_COVER_SCENARIOS: Tuple[
    Tuple[str, str, str, str, str, str, str], ...
] = (
    # stand p4s1 - three large trees, three different crown-equation families
    ("ccv-p4s1-psme", "p4s1", "PSME", "12", "60", "0",
     "BR-CCV-LRG; BR-CCV-OVL"),
    ("ccv-p4s1-pial", "p4s1", "PIAL", "18", "70", "0",
     "BR-CCV-LRG; BR-CCV-OVL"),
    ("ccv-p4s1-abba", "p4s1", "ABBA", "8", "40", "0",
     "BR-CCV-LRG; BR-CCV-OVL"),
    # stand p4s2 - the 4.5 ft height boundary triple (large vs small equation)
    ("ccv-p4s2-psme-ht46", "p4s2", "PSME", "3", "4.6", "0", "BR-CCV-LRG"),
    ("ccv-p4s2-psme-ht45", "p4s2", "PSME", "3", "4.5", "0", "BR-CCV-SML"),
    ("ccv-p4s2-psme-ht44", "p4s2", "PSME", "3", "4.4", "0", "BR-CCV-SML"),
    # stand p4s3 - a single tree (isolates one tree's crown area exactly)
    ("ccv-p4s3-quru", "p4s3", "QURU", "20", "80", "0", "BR-CCV-LRG"),
    # stand p4s4 - zero/nonpositive geometry: C++ returns 0 crown area
    ("ccv-p4s4-psme-ht0", "p4s4", "PSME", "12", "0", "0", "BR-CCV-ZERO"),
    ("ccv-p4s4-psme-htneg", "p4s4", "PSME", "12", "-5", "0", "BR-CCV-ZERO"),
    ("ccv-p4s4-psme-dbh0", "p4s4", "PSME", "0", "60", "0", "BR-CCV-ZERO"),
    # stand p4s5 - four identical large trees, exercising overlap saturation
    ("ccv-p4s5-pico-a", "p4s5", "PICO", "24", "90", "0", "BR-CCV-OVL"),
    ("ccv-p4s5-pico-b", "p4s5", "PICO", "24", "90", "0", "BR-CCV-OVL"),
    ("ccv-p4s5-pico-c", "p4s5", "PICO", "24", "90", "0", "BR-CCV-OVL"),
    ("ccv-p4s5-pico-d", "p4s5", "PICO", "24", "90", "0", "BR-CCV-OVL"),
    # stand p4s6 - a single tree with an unknown species: the harness's
    # fail-closed SMT_GetIdx guard makes this an EXPECTED model error, which
    # also suppresses the stand aggregate (group-status reconciliation).
    ("ccv-p4s6-unknown", "p4s6", "ZZZZ", "12", "60", "1",
     "BR-CCV-LRG (unknown species -> expected model error)"),
)


#: Tolerance-policy route keys each Phase 4 mode's manifest must cite, in
#: deterministic order. Namespaced under ``<mode>_p4`` so the frozen Phase 2
#: canonical key sets stay byte-stable.
PHASE4_ROUTE_KEYS: Dict[str, Tuple[str, ...]] = {
    "consume": (
        "canopy", "duff_depth", "duff_percent", "durations",
        "emissions_expanded", "emissions_legacy", "herb", "litter",
        "litter_cp", "mineral_soil", "shrub", "totals", "woody",
    ),
    "litter_eq": ("997", "998"),
    "shrub_herb_eq": ("crown_branch", "crown_foliage", "herb", "shrub"),
    "mortality": ("BolCha", "CroDam", "CroSco"),
    "bark_thick": ("all",),
    "canopy_cover": ("all",),
}

#: The route keys each Phase 4 mode's manifest considers when deriving its
#: ``documented_expected_divergences``. Every route a Phase 4 golden cites is
#: also a candidate divergence route (unlike Phase 2, whose canonical single
#: row could not reach several of the routes its policy section covers); the
#: actual divergence list is still filtered by each entry's real recorded
#: status, so a "verified" route contributes nothing.
PHASE4_DIVERGENCE_KEYS: Dict[str, Tuple[str, ...]] = dict(PHASE4_ROUTE_KEYS)

#: Files whose bytes determine a Phase 4 golden's content. Hashed into every
#: Phase 4 manifest whenever the working tree is dirty, exactly as Phase 2
#: does for its own list.
GENERATOR_SOURCE_FILES_RELATIVE: Tuple[str, ...] = (
    "tests/cpp_parity_live/_golden_manifest.py",
    "tests/cpp_parity_live/_harness_support.py",
    "tests/cpp_parity_live/_output_contract.py",
    "tests/cpp_parity_live/_phase4_contract.py",
    "tests/cpp_parity_live/_proc.py",
    "tests/cpp_parity_live/generate_phase2_goldens.py",
    "tests/cpp_parity_live/generate_phase4_goldens.py",
    "tests/cpp_parity_live/test_cpp_harness_contract.py",
    "tests/cpp_parity_live/tolerance_policy.json",
)

#: Output-file suffixes each Phase 4 mode writes, duplicated from
#: ``_golden_manifest.MODE_OUTPUT_SUFFIXES`` through a direct import rather
#: than a second hardcoded list, so the required-file set below can never
#: drift from the set the generator actually produces.
MODE_OUTPUT_SUFFIXES: Dict[str, Tuple[str, ...]] = {
    mode: tuple(_MODE_OUTPUT_SUFFIXES[mode]) for mode in PHASE4_MODES
}

#: Tolerances that are class-(a) PYTHON-SIDE bounds only. Each one bounds a
#: comparison between two Python values, or between a Python value and a
#: constant hand-transcribed from the pinned C++ source - never between a
#: Python value and a generated C++ golden. They are therefore deliberately
#: NOT recorded in ``tolerance_policy.json``, which is the evidence register
#: for executable Python-vs-C++ golden comparisons only. Access them through
#: :func:`python_contract_epsilon` so every use is named and validated.
PYTHON_CONTRACT_EPSILONS: Dict[str, float] = {
    # Recovering mort_bolchar's effective (B1, B2, B3) by evaluating the
    # function at three points is exact double arithmetic apart from the
    # logit round-trip; 1e-09 is the round-trip's own noise floor.
    "bolchar_coefficient_recovery": 1e-9,
    # F-47/F-50's "is this a ROUNDED unit conversion" test: a rounded
    # conversion of a 3-4 significant-figure coefficient differs from the
    # exact quotient by well under 2e-03 relative, while an unrelated
    # coefficient differs by far more.
    "rounded_conversion_relative_bound": 2e-3,
    # Comparing calc_smoke_emissions' own SI output against the same factor
    # expression evaluated in Python: pure double round-off.
    "emission_factor_expression": 1e-12,
    # Python imperial-vs-SI identity, both sides produced by the same Python
    # call: pure double round-off.
    "imperial_multiplier_identity": 1e-12,
    # CPP_IMPERIAL_MULTIPLIER recomputed from its two pinned constant pairs
    # against the value quoted in F-32's text.
    "imperial_multiplier_value": 1e-13,
    # The same comparison expressed as a relative difference.
    "imperial_multiplier_ratio_relative": 1e-9,
    # The bark-thickness ORACLE-INVARIANT check divides two golden values by
    # each other, so the bound is the six-decimal golden's own quotient noise
    # rather than any Python-vs-C++ tolerance.
    "bark_factor_oracle_invariant": 5e-7,
}


def _apply(
        base: Sequence[str],
        index: Dict[str, int],
        case_id: str,
        overrides: Dict[str, str],
) -> List[str]:
    """
    Return a copy of *base* with ``case_id`` and *overrides* applied.

    :param base: The mode's canonical all-ok row (field values, in schema
        order).
    :param index: Column-name to position map for that mode's schema.
    :param case_id: Value for the row's ``case_id`` column.
    :param overrides: Column-name to value pairs to substitute.
    :returns: A new field list of the same length as *base*.
    :raises KeyError: If an override names a column the schema does not have
        - intentional fail-closed behaviour, so a typo in a scenario
        definition cannot silently produce a row that tests nothing.
    """
    row = list(base)
    row[index["case_id"]] = case_id
    for column, value in overrides.items():
        row[index[column]] = value
    return row


def _required_golden_files(mode: str) -> List[str]:
    """
    Return the absolute paths every committed Phase 4 golden for *mode* must
    contain.

    Derived from the generator's own per-mode output-suffix table rather than
    a second hardcoded list, so a mode that gains or loses an output file
    cannot silently fall out of the required set.

    :param mode: Harness mode name.
    :returns: Absolute paths to the mode's manifest, input CSV and every
        declared output CSV.
    :raises KeyError: If *mode* is not one of :data:`PHASE4_MODES`.
    """
    directory = golden_dir(mode)
    paths = [
        os.path.join(directory, f"{mode}.manifest.json"),
        os.path.join(directory, f"{mode}_in.csv"),
    ]
    paths.extend(
        os.path.join(directory, f"{mode}{suffix}.csv")
        for suffix in MODE_OUTPUT_SUFFIXES[mode]
    )
    return paths


def golden_dir(mode: str) -> str:
    """
    Return the committed Phase 4 golden directory for *mode*.

    :param mode: Harness mode name.
    :returns: Absolute path (may not exist if the dataset was never
        generated in this checkout).
    """
    return os.path.join(GOLDEN_ROOT, mode)


def golden_manifest(mode: str) -> Optional[Dict[str, Any]]:
    """
    Load *mode*'s committed Phase 4 manifest.

    :param mode: Harness mode name.
    :returns: The parsed manifest, or ``None`` if the file does not exist.
    """
    path = os.path.join(golden_dir(mode), f"{mode}.manifest.json")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def golden_rows(mode: str, suffix: str = "") -> List[Dict[str, str]]:
    """
    Read a committed Phase 4 golden output CSV as a list of row dicts.

    :param mode: Harness mode name.
    :param suffix: Output-file suffix (``""`` for a mode's single primary
        file, else e.g. ``"_summary"``).
    :returns: Every data row, as ``{column: raw string value}``.
    :raises FileNotFoundError: If the golden file is absent - callers must
        surface this as an explicit skip or failure, never substitute a
        hardcoded assumption for a missing oracle.
    """
    path = os.path.join(golden_dir(mode), f"{mode}{suffix}.csv")
    with open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def golden_rows_by_case(mode: str, suffix: str = "") -> Dict[str, Dict[str, str]]:
    """
    Read a committed Phase 4 golden output CSV keyed by ``case_id``.

    :param mode: Harness mode name.
    :param suffix: Output-file suffix.
    :returns: ``{case_id: row}``.
    :raises FileNotFoundError: Via :func:`golden_rows`.
    :raises ValueError: If two rows share a ``case_id`` (the golden's own
        one-output-per-input reconciliation would already have failed, so
        this is a fail-closed backstop).
    """
    out: Dict[str, Dict[str, str]] = {}
    for row in golden_rows(mode, suffix):
        case_id = row["case_id"]
        if case_id in out:
            raise ValueError(
                f"duplicate case_id {case_id!r} in {mode}{suffix}.csv"
            )
        out[case_id] = row
    return out


def missing_golden_files() -> List[str]:
    """
    Return every required Phase 4 golden file that is absent or empty.

    Deliberately returns the exact repo-relative paths rather than a boolean:
    a broken checkout must produce an actionable message naming the files,
    never a silent skip. See :func:`require_golden_tree`.

    :returns: Repo-relative paths, sorted, of every required file that does
        not exist or exists with zero bytes.
    """
    missing = []
    for mode in PHASE4_MODES:
        for path in _required_golden_files(mode):
            if not os.path.isfile(path) or os.path.getsize(path) == 0:
                missing.append(
                    os.path.relpath(path, PROJECT_ROOT).replace(os.sep, "/")
                )
    return sorted(missing)


def phase4_approx_kwargs(mode: str, route: str) -> Dict[str, float]:
    """
    Return the ``pytest.approx`` keyword arguments for one Phase 4 output
    route, built from the centrally recorded tolerance.

    A bound that :func:`phase4_tolerance` reports as ``None`` is OMITTED
    rather than passed as ``None``, so the resulting comparison has exactly
    the semantics the policy records:

    - ``atol`` only -> a pure absolute comparison;
    - ``rtol`` only -> a relative comparison against ``pytest.approx``'s own
      default absolute floor;
    - both -> ``max(rtol * expected, atol)``, ``pytest.approx``'s standard
      combined rule.

    :param mode: Harness mode name; the ``_p4`` suffix is added downstream.
    :param route: Route key within that mode's Phase 4 policy section.
    :returns: ``{"abs": atol}``, ``{"rel": rtol}`` or both - never empty,
        because :func:`phase4_tolerance` guarantees at least one bound.
    :raises KeyError: If the section or route does not exist.
    :raises ValueError: Via :func:`phase4_tolerance`, if no bound can be
        resolved.
    """
    atol, rtol = phase4_tolerance(mode, route)
    kwargs: Dict[str, float] = {}
    if atol is not None:
        kwargs["abs"] = atol
    if rtol is not None:
        kwargs["rel"] = rtol
    return kwargs


def phase4_divergence_keys(mode: str) -> List[str]:
    """
    Return the dotted policy keys whose divergence status a Phase 4 manifest
    for *mode* must document.

    :param mode: Harness mode name.
    :returns: Dotted ``<mode>_p4.<route>`` keys in deterministic order.
    :raises KeyError: If *mode* has no Phase 4 contract.
    """
    return [f"{mode}_p4.{route}" for route in PHASE4_DIVERGENCE_KEYS[mode]]


def phase4_policy_keys(mode: str) -> List[str]:
    """
    Return every tolerance-policy key applicable to *mode*'s Phase 4 golden.

    :param mode: Harness mode name.
    :returns: Dotted ``<mode>_p4.<route>`` keys in deterministic order.
    :raises KeyError: If *mode* has no Phase 4 contract.
    """
    return [f"{mode}_p4.{route}" for route in PHASE4_ROUTE_KEYS[mode]]


def phase4_rows(mode: str) -> List[List[str]]:
    """
    Build the complete, ordered Phase 4 input rows for *mode*.

    :param mode: Harness mode name.
    :returns: One field list per scenario, in the mode's schema order.
    :raises KeyError: If *mode* is not one of :data:`PHASE4_MODES`.
    """
    if mode == "consume":
        base = MODES["consume"]["row"]
        return [
            _apply(base, CONSUME_INDEX, case_id, overrides)
            for case_id, overrides, _branches in CONSUME_SCENARIOS
        ]
    if mode == "litter_eq":
        return [
            [case_id, "0", equ, load, moist]
            for case_id, equ, load, moist, _branches in LITTER_EQ_SCENARIOS
        ]
    if mode == "shrub_herb_eq":
        base = MODES["shrub_herb_eq"]["row"]
        return [
            _apply(base, SHRUB_HERB_INDEX, case_id, overrides)
            for case_id, overrides, _branches in SHRUB_HERB_EQ_SCENARIOS
        ]
    if mode == "mortality":
        base = MODES["mortality"]["row"]
        return [
            _apply(base, MORTALITY_INDEX, case_id, overrides)
            for case_id, overrides, _branches in MORTALITY_SCENARIOS
        ]
    if mode == "bark_thick":
        return [
            [case_id, expect_error, species, dbh]
            for case_id, species, dbh, expect_error, _branches
            in BARK_THICK_SCENARIOS
        ]
    if mode == "canopy_cover":
        return [
            [case_id, expect_error, stand_id, species, dbh, ht]
            for case_id, stand_id, species, dbh, ht, expect_error, _branches
            in CANOPY_COVER_SCENARIOS
        ]
    raise KeyError(f"unknown Phase 4 mode: {mode!r}")


def phase4_scenario_branches(mode: str) -> Dict[str, str]:
    """
    Return ``{case_id: branch-id text}`` for *mode*'s Phase 4 scenarios.

    Used by the traceability-reconciliation tests so the branch IDs a
    scenario claims to exercise are readable from code, not only from the
    matrix CSV.

    :param mode: Harness mode name.
    :returns: Mapping of case ID to the branch IDs that scenario exercises.
    :raises KeyError: If *mode* is not one of :data:`PHASE4_MODES`.
    """
    if mode == "consume":
        return {c: b for c, _o, b in CONSUME_SCENARIOS}
    if mode == "litter_eq":
        return {c: b for c, _e, _l, _m, b in LITTER_EQ_SCENARIOS}
    if mode == "shrub_herb_eq":
        return {c: b for c, _o, b in SHRUB_HERB_EQ_SCENARIOS}
    if mode == "mortality":
        return {c: b for c, _o, b in MORTALITY_SCENARIOS}
    if mode == "bark_thick":
        return {c: b for c, _s, _d, _e, b in BARK_THICK_SCENARIOS}
    if mode == "canopy_cover":
        return {c: b for c, _s, _sp, _d, _h, _e, b in CANOPY_COVER_SCENARIOS}
    raise KeyError(f"unknown Phase 4 mode: {mode!r}")


def phase4_tolerance(
        mode: str,
        route: str,
) -> Tuple[Optional[float], Optional[float]]:
    """
    Return the centrally recorded ``(atol, rtol)`` for one Phase 4 output
    route.

    This is the ONLY way a Phase 4 parity test may obtain a tolerance for a
    Python-vs-C++ golden comparison: the number, its unit and the measured
    evidence that justifies it live in ``tolerance_policy.json``, never as a
    literal in a test module.

    A route whose own entry records no bound falls back to the single sibling
    entry sharing its declared ``column_group`` that does record one. That
    fallback is deliberate and narrow: entries sharing a ``column_group``
    classify the SAME output column of the SAME file by equation route, so a
    bound derived from that column's own output resolution is a property of
    the column rather than of the route (e.g. ``litter_eq_p4.997``, whose
    divergence no tolerance can honestly bound, still needs the ``con_tac``
    column's resolution bound to express its desired-behaviour assertion).
    Anything else fails closed.

    :param mode: Harness mode name; the ``_p4`` suffix is added here.
    :param route: Route key within that mode's Phase 4 policy section.
    :returns: ``(atol, rtol)``, at least one of which is not ``None``.
    :raises KeyError: If the section or route does not exist.
    :raises ValueError: If neither the entry nor exactly one ``column_group``
        sibling records a tolerance.
    """
    section = f"{mode}_p4"
    policy = load_tolerance_policy()
    if section not in policy:
        raise KeyError(f"no Phase 4 tolerance-policy section {section!r}")
    entries = policy[section]
    if route not in entries:
        raise KeyError(f"no route {route!r} in policy section {section!r}")
    entry = entries[route]
    if entry.get("atol") is not None or entry.get("rtol") is not None:
        return entry.get("atol"), entry.get("rtol")

    group = entry.get("column_group")
    if group is None:
        raise ValueError(
            f"{section}.{route} records no atol/rtol and declares no "
            "column_group, so no bound can be resolved for it - record the "
            "measured evidence in tolerance_policy.json rather than "
            "hardcoding a number in a test"
        )
    siblings = [
        (name, other) for name, other in entries.items()
        if name != route
        and other.get("column_group") == group
        and (other.get("atol") is not None or other.get("rtol") is not None)
    ]
    if len(siblings) != 1:
        raise ValueError(
            f"{section}.{route} records no atol/rtol and its column_group "
            f"{group!r} has {len(siblings)} sibling entries that do; exactly "
            "one is required for the fallback to be unambiguous"
        )
    _name, sibling = siblings[0]
    return sibling.get("atol"), sibling.get("rtol")


def python_contract_epsilon(name: str) -> float:
    """
    Return a named class-(a) PYTHON-SIDE tolerance.

    Separate from :func:`phase4_tolerance` on purpose: these bound
    Python-vs-Python or Python-vs-transcribed-constant comparisons and make
    no executable C++ parity claim, so they are not evidence records in
    ``tolerance_policy.json``.

    :param name: Key in :data:`PYTHON_CONTRACT_EPSILONS`.
    :returns: The epsilon.
    :raises KeyError: If *name* is not registered - a test may not invent an
        unnamed epsilon.
    """
    if name not in PYTHON_CONTRACT_EPSILONS:
        raise KeyError(
            f"unregistered Python-contract epsilon {name!r}; add it to "
            "PYTHON_CONTRACT_EPSILONS with a comment saying what it bounds"
        )
    return PYTHON_CONTRACT_EPSILONS[name]


def require_golden_tree() -> None:
    """
    Fail closed unless the complete committed Phase 4 golden dataset is
    present.

    A missing, empty or partially checked-out Phase 4 golden dataset is a
    REPOSITORY defect, not an environment difference: the dataset is
    committed (see the ``.gitignore`` negations for
    ``tests/test_data/test_golden_output/phase4/``), so a correct checkout
    always has it. Every Phase 4 parity module calls this at import time, so
    the failure surfaces as a loud collection error naming the exact missing
    files rather than as a silent skip.

    :returns: None.
    :raises FileNotFoundError: If any required file is missing or empty.
    """
    missing = missing_golden_files()
    if missing:
        raise FileNotFoundError(
            "the committed Phase 4 golden dataset is incomplete - this is a "
            "repository defect, not a skippable environment difference. "
            "Missing or empty:\n"
            + "\n".join(f"  - {path}" for path in missing)
            + "\nRestore them from git, or regenerate with "
              "tests/cpp_parity_live/generate_phase4_goldens.py (needs the "
              "live MSVC/CMake/Ninja toolchain)."
        )
