#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
_phase6_contract.py - Phase 6 investigation A golden-dataset contract:
default-emissions-equivalence scenario matrix (harness-contract §8.3's
"same-group" experiment).

Builds **no new harness mode**: every scenario below is driven through the
already-qualified ``consume`` mode's existing, unchanged input schema
(``ef_flame_group``/``ef_smolder_group``/``ef_duff_group`` were already added
by Phase 2 revision 7), exactly as ``_phase4_contract.py`` reuses the six
Phase 2 modes. This module lives on its own (not folded into
``_phase4_contract.py``) so editing it cannot move Phase 4's own committed
manifests' ``generator_source_sha256`` — the same reasoning
``_phase5_contract.py``'s docstring gives for its own separate module.

**The experiment (gate0/05-harness-contract.md §8.3).** Python's ``default``
emissions mode applies ONE emission-factor group identically to both flaming
and smoldering consumption, with duff folded undifferentiated into
smoldering (``emission_calcs.py``'s ``mode == 'default'`` branch never reads
``duff_load`` at all). C++ has no ``default`` dispatch path — only ``ES_Calc``
(``legacy``) and ``ES_Calc_NEW`` (``expanded``), selected by ``gf_CriInt``.
The approved plan's question: does configuring ``ES_Calc_NEW`` with
``ef_flame_group == ef_smolder_group == ef_duff_group`` (a "same-group"
configuration) reproduce Python's ``default`` on the 14 flaming/smoldering
totals both sides populate?

**A structural reason to expect agreement, verified directly in this
module's own investigation (not merely assumed).** ``ES_Calc_NEW``
(``bur_brn.cpp:2381-2484``) computes each smoldering total as
``gf_s* * d_Smolder + gf_d* * d_Duff`` (coarse-wood-smoldering factor times
coarse load, PLUS duff factor times duff load) — structurally identical to
Python's ``expanded`` mode, which computes
``e_smo[species] + e_duf[species]`` where
``coarse_smo = max(s_kg - d_kg, 0)`` (``emission_calcs.py:292,317-319``).
When ``ef_smolder_group == ef_duff_group``, Python's sum reduces to
``factor * (coarse_smo + d_kg) = factor * s_kg`` whenever ``d_kg <= s_kg``
(always true physically — duff is a subset of total smoldering
consumption), which is EXACTLY what Python's own ``default`` mode computes
directly (``pm10_f * s_kg * unit_conv``, no duff term at all). So a
same-group ``expanded`` call and a matching-group ``default`` call are
expected to agree on Python's own side purely algebraically — the open
question this dataset answers is whether the REAL, COMPILED
``CM_Mngr -> BCM_Mngr -> Burnup -> ES_Calc_NEW`` pipeline behaves the same
way the pinned source's structure suggests, not merely whether the
Python-side algebra is self-consistent.

Scenario-matrix design rule (equivalence partitions, not a Cartesian
product): 3 same-group scenarios at 3 different group values (proving the
hypothesis generalises, not a lucky coincidence at one group), plus 1
mismatched-group NEGATIVE CONTROL proving the comparison methodology can
actually detect non-equivalence (i.e. the positive results are not simply
because any C++ ``expanded`` configuration happens to match Python
``default`` regardless of group).

Function order: module constants first, then top-level functions alphabetized
private-then-public, per AGENTS.md.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

from tests._support import PROJECT_ROOT, TEST_GOLDEN_DIR
from tests.cpp_parity_live._golden_manifest import (
    load_tolerance_policy,
    MODE_OUTPUT_SUFFIXES as _MODE_OUTPUT_SUFFIXES,
)
from tests.cpp_parity_live.test_cpp_harness_contract import MODES

#: Root of the Phase 6 golden tree. Sibling of ``phase2/``/``phase4/``/
#: ``phase5/``; never merged with any of them, never regenerated by their
#: generators.
GOLDEN_ROOT: str = os.path.join(TEST_GOLDEN_DIR, "phase6")

#: Dataset identifier stamped into every Phase 6 manifest's ``dataset`` field.
DATASET_NAME: str = "phase6"

#: Phase 6 investigation A builds no new harness mode - it reuses the
#: already-qualified ``consume`` mode unchanged, exactly as Phase 4 does.
PHASE6_MODES: Tuple[str, ...] = ("consume",)

#: Column-name -> index for the 49-column consume input schema, derived
#: from the harness's own header constant (a fresh copy, not imported from
#: ``_phase4_contract.py``, so this module's own hash-tracked dependency
#: list stays exactly what it reads).
CONSUME_INDEX: Dict[str, int] = {
    name: i for i, name in enumerate(MODES["consume"]["header"])
}

#: Output-file suffixes ``consume`` writes, imported through
#: ``_golden_manifest.MODE_OUTPUT_SUFFIXES`` so this can never drift from
#: what the generator actually produces.
MODE_OUTPUT_SUFFIXES: Dict[str, Tuple[str, ...]] = {
    mode: tuple(_MODE_OUTPUT_SUFFIXES[mode]) for mode in PHASE6_MODES
}

#: This dataset's own generation-time dependencies, hashed into every
#: manifest whenever the repo is dirty.
GENERATOR_SOURCE_FILES_RELATIVE: Tuple[str, ...] = (
    "tests/cpp_parity_live/_golden_manifest.py",
    "tests/cpp_parity_live/_harness_support.py",
    "tests/cpp_parity_live/_phase6_contract.py",
    "tests/cpp_parity_live/_proc.py",
    "tests/cpp_parity_live/generate_phase2_goldens.py",
    "tests/cpp_parity_live/generate_phase6_goldens.py",
    "tests/cpp_parity_live/test_cpp_harness_contract.py",
    "tests/cpp_parity_live/tolerance_policy.json",
)

# ===========================================================================
# consume scenarios - the same-group experiment
#
# Every row starts from the Phase 2 canonical all-ok ``consume`` row
# (MODES["consume"]["row"]) and overrides ONLY the ef_*_group columns, so no
# unintended fuel/environment difference can masquerade as a routing
# difference. The base row's own critical_intensity_kw_m is already 50
# (>= 0), so every scenario already selects ES_Calc_NEW without an override.
# ===========================================================================

#: ``(case_id, {column: value}, "branch id(s) exercised")``.
CONSUME_SCENARIOS: Tuple[Tuple[str, Dict[str, str], str], ...] = (
    ("default-equiv-g1", {
        "ef_flame_group": "1", "ef_smolder_group": "1", "ef_duff_group": "1",
    }, "BR-EMI-DEFAULT-EQUIV"),
    ("default-equiv-g3", {
        "ef_flame_group": "3", "ef_smolder_group": "3", "ef_duff_group": "3",
    }, "BR-EMI-DEFAULT-EQUIV"),
    ("default-equiv-g8", {
        "ef_flame_group": "8", "ef_smolder_group": "8", "ef_duff_group": "8",
    }, "BR-EMI-DEFAULT-EQUIV"),
    # Negative control: groups deliberately mismatched (Phase 4's own
    # emis-expanded-g258 configuration) - proves this dataset's comparison
    # methodology genuinely discriminates non-equivalent configurations
    # rather than trivially agreeing regardless of group.
    ("default-mismatch-control", {
        "ef_flame_group": "2", "ef_smolder_group": "5", "ef_duff_group": "8",
    }, "BR-EMI-DEFAULT-EQUIV-NEGCTRL"),
)


def _apply(
        base: Sequence[str],
        index: Dict[str, int],
        case_id: str,
        overrides: Dict[str, str],
) -> List[str]:
    """
    Return a copy of *base* with ``case_id`` and *overrides* applied.

    :param base: The mode's canonical all-ok row (field values, in schema
        order).
    :param index: Column-name to position map for that mode's schema.
    :param case_id: Value for the row's ``case_id`` column.
    :param overrides: Column-name to value pairs to substitute.
    :returns: A new field list of the same length as *base*.
    :raises KeyError: If an override names a column the schema does not have
        - fail-closed, so a typo in a scenario definition cannot silently
        produce a row that tests nothing.
    """
    row = list(base)
    row[index["case_id"]] = case_id
    for column, value in overrides.items():
        row[index[column]] = value
    return row


def _required_golden_files(mode: str) -> List[str]:
    """
    Return the absolute paths every committed Phase 6 golden for *mode*
    must contain.

    :param mode: Harness mode name.
    :returns: Absolute paths to the mode's manifest, input CSV, and every
        declared output CSV.
    :raises KeyError: If *mode* is not one of :data:`PHASE6_MODES`.
    """
    directory = golden_dir(mode)
    paths = [
        os.path.join(directory, f"{mode}.manifest.json"),
        os.path.join(directory, f"{mode}_in.csv"),
    ]
    paths.extend(
        os.path.join(directory, f"{mode}{suffix}.csv")
        for suffix in MODE_OUTPUT_SUFFIXES[mode]
    )
    return paths


def golden_dir(mode: str) -> str:
    """
    Return the committed Phase 6 golden directory for *mode*.

    :param mode: Harness mode name.
    :returns: Absolute path (may not exist if the dataset was never
        generated in this checkout).
    """
    return os.path.join(GOLDEN_ROOT, mode)


def golden_manifest(mode: str) -> Optional[Dict[str, Any]]:
    """
    Load *mode*'s committed Phase 6 manifest.

    :param mode: Harness mode name.
    :returns: The parsed manifest, or ``None`` if the file does not exist.
    """
    path = os.path.join(golden_dir(mode), f"{mode}.manifest.json")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def golden_rows(mode: str, suffix: str = "") -> List[Dict[str, str]]:
    """
    Read a committed Phase 6 golden output CSV as a list of row dicts.

    :param mode: Harness mode name.
    :param suffix: Output-file suffix (e.g. ``"_summary"``).
    :returns: Every data row, as ``{column: raw string value}``.
    :raises FileNotFoundError: If the golden file is absent.
    """
    import csv
    path = os.path.join(golden_dir(mode), f"{mode}{suffix}.csv")
    with open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def golden_rows_by_case(mode: str, suffix: str = "") -> Dict[str, Dict[str, str]]:
    """
    Read a committed Phase 6 golden output CSV, keyed by ``case_id``.

    :param mode: Harness mode name.
    :param suffix: Output-file suffix.
    :returns: ``{case_id: row dict}``.
    """
    return {row["case_id"]: row for row in golden_rows(mode, suffix)}


def missing_golden_files() -> List[str]:
    """
    Return every required Phase 6 golden file that is absent or empty.

    :returns: Repo-relative paths, sorted, of every required file that
        does not exist or exists with zero bytes.
    """
    missing = []
    for mode in PHASE6_MODES:
        for path in _required_golden_files(mode):
            if not os.path.isfile(path) or os.path.getsize(path) == 0:
                missing.append(
                    os.path.relpath(path, PROJECT_ROOT).replace(os.sep, "/")
                )
    return sorted(missing)


def phase6_divergence_keys(mode: str) -> List[str]:
    """
    Return the dotted policy keys whose divergence status a Phase 6
    manifest for *mode* must document.

    :param mode: Harness mode name.
    :returns: Dotted ``<mode>_p6.<route>`` keys, deterministic order.
    :raises KeyError: If *mode* is not one of :data:`PHASE6_MODES`.
    """
    return phase6_policy_keys(mode)


def phase6_policy_keys(mode: str) -> List[str]:
    """
    Return every tolerance-policy key applicable to *mode*'s Phase 6 golden.

    :param mode: Harness mode name.
    :returns: Dotted ``<mode>_p6.<route>`` keys, deterministic order.
    :raises KeyError: If *mode* is not one of :data:`PHASE6_MODES`.
    """
    if mode != "consume":
        raise KeyError(f"unknown Phase 6 mode: {mode!r}")
    return [f"consume_p6.{case_id}" for case_id, _o, _b in CONSUME_SCENARIOS]


def phase6_rows(mode: str) -> List[List[str]]:
    """
    Build the complete, ordered Phase 6 input rows for *mode*.

    :param mode: Harness mode name.
    :returns: One field list per scenario, in the mode's schema order.
    :raises KeyError: If *mode* is not one of :data:`PHASE6_MODES`.
    """
    if mode != "consume":
        raise KeyError(f"unknown Phase 6 mode: {mode!r}")
    base = MODES["consume"]["row"]
    return [
        _apply(base, CONSUME_INDEX, case_id, overrides)
        for case_id, overrides, _branches in CONSUME_SCENARIOS
    ]


def require_golden_tree() -> None:
    """
    Fail closed unless the complete committed Phase 6 golden dataset is
    present.

    :returns: None.
    :raises FileNotFoundError: If any required file is missing or empty.
    """
    missing = missing_golden_files()
    if missing:
        raise FileNotFoundError(
            "the committed Phase 6 golden dataset is incomplete - this is a "
            "repository defect, not a skippable environment difference. "
            "Missing or empty:\n"
            + "\n".join(f"  - {path}" for path in missing)
            + "\nRestore them from git, or regenerate with "
              "tests/cpp_parity_live/generate_phase6_goldens.py (needs the "
              "live MSVC/CMake/Ninja toolchain)."
        )
