#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
test_soil_campbell_contract.py - Phase 5 Python-side coverage for
``soil_heat_campbell`` (``src/pyfofem/components/soil_heating.py``).

**Assertion classes (required module declaration):**

- Class **(a) Python contract tests** - nominal behaviour, ``duff``/
  ``non_duff`` model routing, input validation/boundaries, output
  DataFrame structure (index/columns/units/finiteness), repeatability, and
  oracle-independent physical invariants (e.g. a zero fire-intensity
  series must not raise the soil above its starting temperature). These
  make no C++ parity claim.
- Class **(b) source-relation checks** - ``test_*_source_relation`` below,
  which compare Python constants against values hand-transcribed from the
  pinned C++ source with the ``file:line`` cited in each docstring. NOT
  executable parity.
- Class **(c) manifested executable C++ parity - NOT PRESENT in this
  module, by design.** See the note below and the companion module.

**CORRECTED 2026-09-18 (F-70 comprehensive-suite Campbell-backend
consolidation pass).** The paragraph below (preserved for history) is
STALE: F-52's "structurally different models" conclusion is SUPERSEDED
(see ``gate0/04-findings.md`` F-52/F-70). A real, isolated
``bulk_density``/``particle_density`` unit-conversion transcription error
was found and fixed (:func:`_campbell_newton_node_update`'s ``cp[i]``
heat-capacity term, formerly inlined directly in ``_soiltemp_step``, used
``bd`` as an absolute value, not a ratio); all 11 committed Phase 5
scenarios (5 families x both routes) now match the live C++ harness to
well under 0.01 degC over their whole recorded trajectories.
``tests/cpp_parity_live/tolerance_policy.json``'s ``soil_campbell.duff``/
``nonduff`` routes are now ``"status": "verified"`` (``atol=0.01`` degC) —
NOT ``"unverified"``/``"contract_only"`` as the historical paragraph below
states. Class (c) parity tests now DO exist, in
``test_soil_campbell_characterization.py`` (re-measured, no longer
mere characterization) and ``tests/cpp_parity_live/test_soil_solver_diagnostic_comparison.py``
(a live 48-field first-sub-iteration crosswalk against a rebuilt C++
diagnostic binary). This module itself still deliberately stays to
classes (a)/(b) only — that scoping choice is unchanged — but the reason
is now "these tests don't need a live C++ build", not "parity doesn't
exist yet".

**HISTORICAL (2026-09-03, F-17/F-51/F-52 triage pass) — superseded by the
correction above, preserved for the record.** Why no class (c) tests
here, and where they actually live (F-17 / F-51 / F-52). The Phase 5
golden dataset
(``tests/test_data/test_golden_output/soil_campbell/soil_campbell/``, generated by
``tests/cpp_parity_live/generate_soil_campbell_goldens.py``) exists and is real,
manifested, and verified deterministic, and real Python-vs-C++ numeric
comparisons DO exist — in the sibling module
``test_soil_campbell_characterization.py`` — but they are explicitly
**cross-implementation characterization, not parity**: F-52
(``gate0/04-findings.md``) measured that Python's ``soil_heat_campbell()``
and C++'s ``soiltemp_step`` are structurally different models (C++
integrates coupled moisture/vapor/latent-heat state and an ambient
radiative floor absent from Python), not one model at two numerical
precisions or one model with a mismatched constant table — a 16-49 degC
divergence persists even after aligning every Python-consumed soil-property
input to the pinned C++ table, for every family including
``"coarse-silty"``/C++ ``Coarse-Silt`` (F-51's one matching family). Every
``soil_campbell`` route in ``tolerance_policy.json`` therefore stays
honestly ``"status": "unverified"``/``"contract_only"`` (real null
``atol``/``rtol``) — no measured divergence, however documented, is
converted into a tolerance bound. This module keeps to classes (a)/(b)
only, deliberately, so a reader does not mistake either kind of test for a
parity claim.

Also documents one real Python/C++ CONTRACT difference discovered while
building this module, independent of any numeric divergence:
``soil_heat_campbell``'s ``model`` parameter is an explicit caller choice
(``"duff"``/``"non_duff"``); C++'s ``SH_Mngr`` instead INFERS the route
from whether ``duff_dep_pre_in > 0`` (harness-contract section 7). Neither
side is wrong - they are simply different points in the same pipeline
(Python expects the caller to have already decided which surface-flux
model applies; C++ decides it internally from a duff-depth input Python's
function does not take at all) - but a caller porting scenarios between
the two schemas must make that routing decision explicitly, since Python
has no ``duff_dep_pre_in``-equivalent auto-selection.

Function order: private helpers first, then public test functions, each
group alphabetized, per AGENTS.md.
"""
from __future__ import annotations

import inspect

import numpy as np
import pandas as pd
import pytest

import pyfofem.components.soil_heating as sh
from pyfofem.components.soil_heating import _SOIL_FAMILY_DEFAULTS, soil_heat_campbell

pytestmark = pytest.mark.soil_solver

#: 13 depths (cm), matching the Phase 5 BR-SOI-DUFF/NODUFF scenario
#: matrix's use of the C++ eC_Lay==14 (Surface + 13 layers) convention.
_DEPTHS = list(range(1, 14))

#: A short, clearly-decaying fire-intensity series (mirrors
#: ``_soil_campbell_contract.py``'s shared side-file formula so the same physical
#: scenario shape is exercised on both sides of the port, even though no
#: numeric comparison is attempted yet - see the module docstring).
_N_STEPS = 20
_TIMES_S = [i * 15.0 for i in range(_N_STEPS)]
_WL_SERIES = [max(0.0, 50.0 - 3.0 * i) for i in range(_N_STEPS)]
_HS_SERIES = [max(0.0, 10.0 - 0.5 * i) for i in range(_N_STEPS)]


def _duff_params(**overrides) -> dict:
    """
    Build a valid ``duff_params`` dict for :func:`soil_heat_campbell`'s
    ``model="duff"`` path, with optional field overrides.

    :param overrides: Fields to override in the base dict.
    :returns: A ``duff_params`` dict.
    """
    base = dict(duff_load=5.0, duff_depth=2.0, duff_moisture=60.0, pct_consumed=50.0)
    base.update(overrides)
    return base


def _soil_params(soil_family: str = "coarse-silty", start_water: float = 0.10,
                  start_temp: float = 21.0, **overrides) -> dict:
    """
    Build a valid ``soil_params`` dict for :func:`soil_heat_campbell`, with
    optional field overrides.

    ``"coarse-silty"`` is the default because it is the one soil family
    F-51 confirms has C++-matching physical constants - the most credible
    target for any future class (c) comparison built on top of this
    module's fixtures.

    :param soil_family: One of :data:`_SOIL_FAMILY_DEFAULTS`'s keys.
    :param start_water: Starting volumetric water content (m3/m3).
    :param start_temp: Starting soil temperature (degC).
    :param overrides: Additional fields to override in the base dict.
    :returns: A ``soil_params`` dict.
    """
    base = dict(soil_family=soil_family, start_water=start_water, start_temp=start_temp)
    base.update(overrides)
    return base


def test_both_routes_share_the_same_coupled_backend(monkeypatch):
    """Class (a) architecture invariant, added 2026-09-18 (F-70
    Campbell-backend consolidation pass). Both ``model="duff"`` and
    ``model="non_duff"`` must reach the exact same coupled-solver
    backend -- :func:`_run_coupled_soil_sim` (and, transitively,
    :func:`_soiltemp_step`) -- not two parallel implementations that
    happen to look similar. Proven by monkeypatching
    ``_run_coupled_soil_sim`` itself and recording the ``id()`` of the
    function object each route actually calls, rather than merely
    asserting the routes' outputs share a schema (already covered by
    :func:`test_duff_vs_non_duff_are_explicit_caller_choices_not_auto_routed`)."""
    calls = []
    real_run = sh._run_coupled_soil_sim

    def _spy(state, dt, forcing_fn, done_fn, start_temp):
        calls.append(id(_spy))
        return real_run(state, dt, forcing_fn, done_fn, start_temp)

    monkeypatch.setattr(sh, "_run_coupled_soil_sim", _spy)

    soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    soil_heat_campbell(
        "non_duff", {}, _soil_params(), _DEPTHS,
        burnup_intensity=_WL_SERIES, burnup_intensity_hs=_HS_SERIES,
        burnup_times=_TIMES_S,
    )

    assert len(calls) == 2
    assert calls[0] == calls[1] == id(_spy)


def test_diagnostic_hooks_default_to_no_op(monkeypatch):
    """Class (a) architecture invariant, added 2026-09-18 (F-70
    Campbell-backend consolidation pass). The public facade must never
    itself supply ``on_subiter``/``on_surface_update`` to
    :func:`_soiltemp_step` -- both diagnostic hooks stay at their
    ``None`` default for every real caller, so their presence in
    :func:`_campbell_newton_boundary_init`/
    :func:`_campbell_newton_node_update`'s extracted signatures changes
    nothing about ordinary behavior. Proven by monkeypatching
    ``_soiltemp_step`` itself and inspecting the actual keyword/
    positional arguments :func:`_run_coupled_soil_sim` passes it, rather
    than only reading the default-parameter source."""
    calls = []
    real_step = sh._soiltemp_step

    def _spy(state, r_rabs, dt, on_subiter=None, on_surface_update=None):
        calls.append((on_subiter, on_surface_update))
        return real_step(state, r_rabs, dt, on_subiter, on_surface_update)

    monkeypatch.setattr(sh, "_soiltemp_step", _spy)

    soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)

    assert len(calls) > 0
    assert all(hooks == (None, None) for hooks in calls)


def test_duff_route_produces_finite_dataframe():
    """Class (a). The ``model="duff"`` path must return a fully finite
    DataFrame (no NaN/Inf) - a solver instability would otherwise surface
    only as a silent downstream NaN."""
    df = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    assert np.isfinite(df.to_numpy()).all()


def test_duff_vs_non_duff_are_explicit_caller_choices_not_auto_routed():
    """Class (a) contract note. Unlike C++'s SH_Mngr (which infers the
    route from duff_dep_pre_in > 0), soil_heat_campbell has no field that
    silently changes which model runs - passing "duff" always takes the
    duff-flux path and "non_duff" always takes the burnup-intensity path,
    regardless of what duff_params/burnup_* values happen to be set to."""
    duff_df = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    non_duff_df = soil_heat_campbell(
        "non_duff", {}, _soil_params(), _DEPTHS,
        burnup_intensity=_WL_SERIES, burnup_intensity_hs=_HS_SERIES,
        burnup_times=_TIMES_S,
    )
    # Both routes are independently well-formed and are not required to
    # agree with each other - they model physically different surface
    # fluxes. The contract being tested is that each stays on its own path.
    assert list(duff_df.columns) == list(non_duff_df.columns)
    assert duff_df.index.name == non_duff_df.index.name == "time_min"


def test_first_recorded_row_is_post_first_step_not_raw_init():
    """Class (a). CORRECTED 2026-09-18 (F-70 comprehensive-suite
    reconciliation pass): this test's original name/assertion claimed
    every column at ``time_min == 0`` equals ``soil_params['start_temp']``
    exactly. That claim was itself wrong about the documented contract
    (see :func:`soil_heat_campbell`'s own docstring, corrected alongside
    this test): the first recorded row is the state after the FIRST
    Newton-converged timestep, not the raw pre-simulation initial
    condition -- matching the pinned C++ harness's own ``time_index == 0``
    convention exactly (independently verified: Phase 5 golden scenario
    SOI-NOD-01's own ``time_index=0`` surface reading is 38.849651 degC
    against a 21.0 degC harness ambient start, i.e. C++ ALSO reports a
    post-step value at index 0, never the raw ambient). This test now
    asserts the real, verifiable structural invariant instead: within one
    short timestep, diffusion has not yet reached the deep layers, so
    depth columns converge back toward ``start_temp`` monotonically with
    depth, and the deepest recorded depth is within a tight, physically
    expected tolerance of ``start_temp``. The surface column is
    deliberately NOT asserted to equal ``start_temp`` -- it is the one
    column guaranteed to have already moved."""
    df = soil_heat_campbell(
        "duff", _duff_params(), _soil_params(start_temp=17.5), _DEPTHS,
    )
    first_row = df.iloc[0].to_numpy()
    deviations = np.abs(first_row - 17.5)
    # Monotonic convergence toward start_temp with depth (index 0 = Surface,
    # increasing index = increasing depth) - each column is no farther from
    # start_temp than the previous, shallower one.
    assert np.all(np.diff(deviations) <= 1e-9)
    # The deepest recorded depth (13cm) has not been reached by one
    # timestep's diffusion and remains within a tight tolerance of
    # start_temp.
    assert deviations[-1] < 1e-4


def test_invalid_model_raises_value_error():
    """Class (a). An unrecognised ``model`` string must raise, not
    silently default to one route."""
    with pytest.raises(ValueError, match="model must be"):
        soil_heat_campbell("bogus", {}, _soil_params(), _DEPTHS)


def test_invalid_soil_family_raises_value_error():
    """Class (a). ``soil_params['soil_family']`` must be one of the five
    recognised families - a typo must raise, not silently fall back to a
    default family's constants."""
    with pytest.raises(ValueError, match="Unrecognised soil_family"):
        soil_heat_campbell(
            "duff", _duff_params(), _soil_params(soil_family="not-a-family"),
            _DEPTHS,
        )


def test_non_duff_route_produces_finite_dataframe():
    """Class (a). The ``model="non_duff"`` path must return a fully finite
    DataFrame."""
    df = soil_heat_campbell(
        "non_duff", {}, _soil_params(), _DEPTHS,
        burnup_intensity=_WL_SERIES, burnup_intensity_hs=_HS_SERIES,
        burnup_times=_TIMES_S,
    )
    assert np.isfinite(df.to_numpy()).all()


def test_output_columns_and_index_contract():
    """Class (a). Column order must be ``['Surface', '<d>cm', ...]`` in
    *depth_layers* order, and the index must be named ``'time_min'``,
    start at 0, and be strictly non-decreasing."""
    depths = [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
    df = soil_heat_campbell("duff", _duff_params(), _soil_params(), depths)
    assert list(df.columns) == ["Surface"] + [f"{d}cm" for d in depths]
    assert df.index.name == "time_min"
    assert df.index[0] == pytest.approx(0.0)
    assert df.index.is_monotonic_increasing


def test_repeated_calls_are_deterministic():
    """Class (a). Two identical calls must produce identical output - no
    hidden global/random state (mirrors the C++ harness's own row15/row16
    determinism self-tests for soil_campbell)."""
    df_a = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    df_b = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    pd.testing.assert_frame_equal(df_a, df_b)


def test_soil_family_defaults_source_relation():
    """Class (b). Pins F-51's measured evidence as an executable
    regression: Python's ``_SOIL_FAMILY_DEFAULTS`` must match the pinned
    C++ ``sr_SE``/``sr_SD`` table
    (``reference/fofem_cpp/FOF_UNIX/fof_se2.h:11-20``,
    ``fof_sd2.h:8-21``; both tables carry identical per-family values)
    for ALL FIVE families, not only ``"coarse-silty"``.

    F-51 originally found only ``"coarse-silty"`` matching, and a since-
    superseded version of this test pinned that as "must NOT silently
    start matching for the other four". That framing is now WRONG: the
    F-70 narrow numerical-compatibility pass (third round) found and
    fixed a real, isolated, directly-evidenced transcription error --
    ``bulk_density``/``particle_density`` were divided by 1000 ("g/m^3
    -> kg/m^3, for this module's own SI convention"), which is harmless
    everywhere ``bd``/``pd`` are used as the ratio ``xs = bd/pd``, but
    silently corrupted the ONE place they are used as an ABSOLUTE
    (non-ratio) value: ``_soiltemp_step``'s own
    ``cp[i] = v[i]*(0.87*bd + 4.18e6*wn[i])/dt`` heat-capacity term --
    see ``gate0/04-findings.md`` F-70 for the live-C++-diagnostic
    evidence (measured pinned ``cp[1]``, dry non-duff first
    sub-iteration: 639.550, vs this dict's pre-fix-derived 105.035).
    ``_SOIL_FAMILY_DEFAULTS`` now stores the pinned tables' RAW,
    unconverted literals for every family -- this genuinely, fully
    resolves F-51 (not just for Coarse-Silt)."""
    # C++ table (fof_se2.h/fof_sd2.h, identical between the two): raw
    # literals, NEVER divided by 1000 anywhere in the pinned solver.
    expected = {
        "loamy-skeletal": dict(bulk_density=0.8e6, particle_density=2.13e6,
                                k_mineral=1.03, vries_shape=0.13, cop_power=6.08),
        "fine-silty": dict(bulk_density=1.3e6, particle_density=2.35e6,
                            k_mineral=2.31, vries_shape=0.071, cop_power=4.14),
        "fine": dict(bulk_density=1.15e6, particle_density=2.35e6,
                     k_mineral=2.21, vries_shape=0.084, cop_power=4.63),
        "coarse-silty": dict(bulk_density=1.23e6, particle_density=2.35e6,
                              k_mineral=2.53, vries_shape=0.103, cop_power=3.43),
        "coarse-loamy": dict(bulk_density=1.3e6, particle_density=2.35e6,
                              k_mineral=2.57, vries_shape=0.106, cop_power=2.93),
    }
    for family, exp in expected.items():
        actual = _SOIL_FAMILY_DEFAULTS[family]
        for field, value in exp.items():
            assert actual[field] == pytest.approx(value), (family, field)

    # extrap_water already matched bit-for-bit for every family before
    # this pass (it was never divided by 1000 -- it is dimensionless,
    # m^3/m^3 -- and is unaffected by this fix); re-pinned here for
    # completeness against the same source table.
    extrap_water = {
        "loamy-skeletal": 0.321, "fine-silty": 0.207, "fine": 0.202,
        "coarse-silty": 0.157, "coarse-loamy": 0.102,
    }
    for family, value in extrap_water.items():
        assert _SOIL_FAMILY_DEFAULTS[family]["extrap_water"] == pytest.approx(value)


def test_wl_hs_efficiency_defaults_source_relation():
    """Class (b). ``efficiency_wl=0.15``/``efficiency_hs=0.10`` (function
    defaults) match C++'s own "use built-in default" fallback exactly:
    ``fof_se.cpp:64-67`` sets ``f_SoilWlEff=0.15``/``f_SoilHsEff=0.10``
    whenever the input percent is negative (the harness's own ``-1``
    sentinel convention), after converting the raw whole-number-percent
    input to a decimal fraction (``fof_se.cpp:62-63``, ``/100.0``) - the
    same units Python's parameters are already in."""
    sig = inspect.signature(soil_heat_campbell)
    assert sig.parameters["efficiency_wl"].default == pytest.approx(0.15)
    assert sig.parameters["efficiency_hs"].default == pytest.approx(0.10)


def test_wrong_depth_layers_length_raises_value_error():
    """Class (a). *depth_layers* must contain exactly 13 values (matching
    C++'s fixed ``eC_Lay==14`` Surface+13-layer convention) - too few or
    too many must raise, never silently truncate/pad."""
    with pytest.raises(ValueError, match="exactly 13 values"):
        soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS[:-1])
    with pytest.raises(ValueError, match="exactly 13 values"):
        soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS + [14])


def test_zero_fire_intensity_never_exceeds_start_temp():
    """Class (a), oracle-independent physical invariant. A non_duff run
    with an all-zero fire-intensity series delivers zero surface flux, so
    the soil column must never exceed its own starting temperature (up to
    solver tolerance) - true regardless of which side (Python or C++, or
    neither) is scientifically "correct", since it follows from energy
    conservation alone, not from matching any oracle."""
    df = soil_heat_campbell(
        "non_duff", {}, _soil_params(start_temp=15.0), _DEPTHS,
        burnup_intensity=[0.0] * _N_STEPS, burnup_intensity_hs=[0.0] * _N_STEPS,
        burnup_times=_TIMES_S,
    )
    assert (df.to_numpy() <= 15.0 + 1e-6).all()
