#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
test_tree_flame_contracts.py - Phase 3 public-contract coverage for
``calc_scorch_ht`` and ``calc_flame_length``.

**Test-category classification** (see the phase plan
``development/plans/2026-08-26-comprehensive-test-suite-plan.md``):

(a) *Python contract/equation test* - asserts documented equations, or
    explicitly identified current Python behaviour including known
    contract defects pinned for visibility, against hand-derived
    expected values. Makes no C++ parity claim, and does not endorse
    defective behaviour as desired API design. **Every test in this
    module is category (a)**; several of them pin findings F-24, F-28,
    F-33 and F-34, which are undocumented or defective current
    behaviour recorded for visibility, not endorsed API design.
(b) *Source-relation cross-check* - hand-derived against a pinned C++
    expression that is not executable in isolation. **None here**; the
    tree/flame source-relation tests live in
    ``tests/unit/test_tree_flame_source_relations.py``.
(c) *Executable C++ parity* - compares against output generated by a
    live pinned-C++ run. **None here, and deliberately so.**

Gate 0 established that C++ ``Calc_Scorch`` (``fof_util.cpp:95-102``)
converts *flame length to scorch height*, and ``Calc_Flame``
(``fof_util.cpp:111-118``) converts *scorch height back to flame
length* - both through the same 0.45/power relationship. Python's
``calc_scorch_ht`` takes *fire intensity* plus optional ambient
temperature and in-stand windspeed, and ``calc_flame_length``'s
fire-intensity modes use Byram / Butler / Thomas equations. They are
different APIs with different inputs and must never be compared as
parity oracles (``gate0/03-cpp-crosswalk.md`` rows 6 and 7). No C++
comparison is therefore attempted anywhere in this module.

Two contract defects recorded by Gate 0 are pinned here as *current
behaviour*, with the divergence stated explicitly rather than hidden:

* **F-24** - ``calc_scorch_ht``'s ``(60 - amb_t)`` denominator has no
  guard, so equations 9 and 10 divide by zero at ``amb_t == 60``.
  Also, the missing-intensity guard is **not** fully dead code; see
  :func:`test_scorch_ht_missing_intensity_guard_fires_for_object_dtype`
  and its inert-for-numeric counterpart.
* **F-28** - ``calc_flame_length`` dispatches ``fl_model`` with
  ``if 'Byram' / if 'Butler' / else``, so any unrecognised string
  (including a typo such as ``'byram'``) silently selects Thomas.

Function order: private helpers first, then public test functions, each
group alphabetized, per AGENTS.md.
"""
from __future__ import annotations

import numpy as np
import pytest

from pyfofem import calc_flame_length, calc_scorch_ht

#: Fire intensities (kW/m) whose two-thirds power is an exact integer, so
#: every equation-8/9 expectation below is a literal hand-computed value
#: rather than a re-execution of the implementation's own expression:
#: ``1 ** (2/3) == 1``, ``125 ** (2/3) == 25``, ``1000 ** (2/3) == 100``,
#: ``8000 ** (2/3) == 400``, ``27000 ** (2/3) == 900``.
_EXACT_CUBE_INTENSITIES = {
    1.0: 1.0,
    125.0: 25.0,
    1000.0: 100.0,
    8000.0: 400.0,
    27000.0: 900.0,
}


def _assert_close(actual: float, expected: float, rel: float = 1e-12) -> None:
    """
    Assert a scalar result matches a hand-derived expectation.

    A relative tolerance of 1e-12 is used rather than an absolute one so
    the same helper serves both the small (metres) and large (percent)
    magnitudes in this module. The tolerance is a floating-point
    round-off allowance only - these are exact closed-form expectations,
    not measurements, so nothing scientific is being absorbed by it.

    :param actual: Value returned by the function under test.
    :param expected: Hand-derived expected value.
    :param rel: Relative tolerance passed through to
        :func:`pytest.approx`.
    :return: None. Raises via ``assert`` on mismatch.
    """
    assert actual == pytest.approx(expected, rel=rel)


def test_flame_length_butler_hand_derived_values():
    """
    Butler mode must evaluate ``0.0175 * I ** (2/3)`` exactly.

    Hand-derived on the exact-cube intensities: ``0.0175 * 100 = 1.75``,
    ``0.0175 * 400 = 7.0``, ``0.0175 * 900 = 15.75``.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_flame_length(1000.0, fl_model="Butler")), 1.75)
    _assert_close(float(calc_flame_length(8000.0, fl_model="Butler")), 7.0)
    _assert_close(float(calc_flame_length(27000.0, fl_model="Butler")), 15.75)


def test_flame_length_byram_hand_derived_values():
    """
    Byram mode must evaluate ``0.0775 * I ** 0.46``.

    ``1000 ** 0.46 == 10 ** 1.38 == 23.9883291901949...``; multiplying by
    0.0775 gives the frozen literal below (independently reproduced as
    ``0.0775 * math.exp(0.46 * math.log(1000.0))``, agreeing to within
    4e-16 relative).

    The 8000 kW/m expectation is ``0.0775 * 8000 ** 0.46``, derived the
    same independent way: ``log(8000) = log(8) + log(1000) =
    2.0794415416798357 + 6.907755278982137 = 8.987196820661973``, times
    0.46 gives ``4.134110537504508``, whose exponential times 0.0775 is
    the frozen literal below (the two routes agree to within 5e-16
    relative). Both values are frozen constants, so this test compares
    against hand-carried numbers rather than re-running the
    implementation's own expression.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_flame_length(1000.0)), 1.8590955122401054)
    _assert_close(float(calc_flame_length(8000.0)), 4.838637606684622)


def test_flame_length_char_ht_mode_hand_derived_values():
    """
    The char-height mode must evaluate ``char_ht * 1.8`` exactly.

    This is the algebraic inverse of the char-height relation the pinned
    mortality source uses (``fof_mrt.cpp:396-397``); the relation itself
    is cross-checked in
    ``tests/unit/test_tree_flame_source_relations.py``. Here it is
    asserted purely as the Python contract.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_flame_length(char_ht=1.0)), 1.8)
    _assert_close(float(calc_flame_length(char_ht=2.5)), 4.5)
    _assert_close(float(calc_flame_length(char_ht=0.0)), 0.0)


def test_flame_length_fire_intensity_takes_precedence_over_char_ht():
    """
    When both ``fire_intensity`` and ``char_ht`` are supplied, the
    fire-intensity branch wins and the char-height argument is ignored.

    Pinned because the function has two independent optional inputs and
    no documented precedence rule; a future refactor that reversed the
    order would silently change results for every caller passing both.

    :return: None. Raises via ``assert`` on mismatch.
    """
    both = float(calc_flame_length(1000.0, char_ht=99.0))
    intensity_only = float(calc_flame_length(1000.0))
    _assert_close(both, intensity_only)


def test_flame_length_negative_intensity_returns_nan():
    """
    A negative fire intensity raised to a fractional power yields NaN
    with a NumPy ``RuntimeWarning`` in every fire-intensity mode.

    Pinned as current behaviour: the function performs no domain
    validation on ``fire_intensity``.

    :return: None. Raises via ``assert`` on mismatch.
    """
    for model in ("Byram", "Butler", "Thomas"):
        with pytest.warns(RuntimeWarning, match="invalid value"):
            result = calc_flame_length(-1.0, fl_model=model)
        assert np.isnan(result)


def test_flame_length_requires_intensity_or_char_ht():
    """
    Calling with neither ``fire_intensity`` nor ``char_ht`` must raise
    ``ValueError`` with the documented diagnostic.

    :return: None. Raises via ``assert`` on mismatch.
    """
    with pytest.raises(ValueError, match="surface fire intensity or char height"):
        calc_flame_length()


def test_flame_length_scalar_matches_length_one_array():
    """
    A scalar call and a length-one array call must agree, for every
    fire-intensity model and for the char-height mode.

    :return: None. Raises via ``assert`` on mismatch.
    """
    for model in ("Byram", "Butler", "Thomas"):
        scalar = float(calc_flame_length(1000.0, fl_model=model))
        arrayed = calc_flame_length(np.array([1000.0]), fl_model=model)
        assert arrayed.shape == (1,)
        _assert_close(float(arrayed[0]), scalar)

    scalar_char = float(calc_flame_length(char_ht=2.0))
    arrayed_char = calc_flame_length(char_ht=np.array([2.0]))
    assert arrayed_char.shape == (1,)
    _assert_close(float(arrayed_char[0]), scalar_char)


def test_flame_length_thomas_hand_derived_values():
    """
    Thomas mode must evaluate ``0.0267 * I ** (2/3)`` exactly.

    Hand-derived on the exact-cube intensities: ``0.0267 * 100 = 2.67``,
    ``0.0267 * 400 = 10.68``, ``0.0267 * 900 = 24.03``.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_flame_length(1000.0, fl_model="Thomas")), 2.67)
    _assert_close(float(calc_flame_length(8000.0, fl_model="Thomas")), 10.68)
    _assert_close(float(calc_flame_length(27000.0, fl_model="Thomas")), 24.03)


@pytest.mark.parametrize(
    "fl_model",
    ["byram", "BYRAM", "butler", "Thomas", "", "not-a-model", "Van Wagner"],
)
def test_flame_length_unrecognised_model_silently_selects_thomas(fl_model):
    """
    Pin Gate 0 finding **F-28**: ``fl_model`` is dispatched with
    ``if 'Byram' / if 'Butler' / else`` in ``tree_flame_calcs.py``, so
    any string that is neither the exact ``'Byram'`` nor the exact
    ``'Butler'`` - including a case variant or an outright typo - falls
    through to the Thomas equation instead of raising. This test
    documents that divergence from a fail-fast contract; it does not
    endorse it.

    :param fl_model: Model string that is not exactly ``'Byram'`` or
        ``'Butler'``.
    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_flame_length(1000.0, fl_model=fl_model)), 2.67)


def test_flame_length_zero_intensity_is_zero():
    """
    Zero fire intensity yields zero flame length in every
    fire-intensity mode (``0 ** p == 0`` for positive ``p``).

    :return: None. Raises via ``assert`` on mismatch.
    """
    for model in ("Byram", "Butler", "Thomas"):
        _assert_close(float(calc_flame_length(0.0, fl_model=model)), 0.0)


def test_scorch_ht_ambient_60_divides_by_zero():
    """
    Pin the second half of Gate 0 finding **F-24**: equations 9 and 10
    divide by ``(60 - amb_t)`` with no guard, so an ambient temperature
    of exactly 60 C yields ``inf`` plus a NumPy ``RuntimeWarning``
    instead of a diagnosed error.

    :return: None. Raises via ``assert`` on mismatch.
    """
    with pytest.warns(RuntimeWarning, match="divide by zero"):
        eq9 = calc_scorch_ht(1000.0, 60.0)
    assert np.isinf(eq9)

    with pytest.warns(RuntimeWarning, match="divide by zero"):
        eq10 = calc_scorch_ht(1000.0, 60.0, 2.0)
    assert np.isinf(eq10)


def test_scorch_ht_ambient_above_60_returns_negative_height():
    """
    An ambient temperature above 60 C flips the sign of the equation-9
    denominator and returns a physically meaningless negative scorch
    height rather than raising or clamping.

    Pinned as current behaviour so a future domain guard is a visible,
    deliberate change. Hand-derived at ``sfi = 1000``, ``amb_t = 80``:
    ``4.4713 * 100 / (60 - 80) = 447.13 / -20 = -22.3565``.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_scorch_ht(1000.0, 80.0)), -22.3565)


def test_scorch_ht_array_broadcast_matches_row_by_row():
    """
    Array evaluation of equations 9 and 10 must equal row-by-row scalar
    evaluation of the same inputs, an oracle-independent metamorphic
    property required by the phase plan.

    :return: None. Raises via ``assert`` on mismatch.
    """
    sfi = np.array([1000.0, 8000.0, 27000.0])
    amb = np.array([20.0, 10.0, 35.0])
    wind = np.array([1.0, 2.0, 3.0])

    eq9_vec = calc_scorch_ht(sfi, amb)
    for i in range(len(sfi)):
        _assert_close(float(eq9_vec[i]), float(calc_scorch_ht(sfi[i], amb[i])))

    eq10_vec = calc_scorch_ht(sfi, amb, wind)
    for i in range(len(sfi)):
        _assert_close(
            float(eq10_vec[i]), float(calc_scorch_ht(sfi[i], amb[i], wind[i]))
        )


def test_scorch_ht_equation_10_hand_derived_value():
    """
    Equation 10 must evaluate
    ``0.74183 * I**(7/6) / (sqrt(0.025574*I + 0.021433*ws**3) * (60 - T))``.

    Hand derivation at ``I = 1000`` kW/m, ``ws = 2`` m/s, ``T = 20`` C:

    * ``1000 ** (7/6) = 1000 * 1000 ** (1/6) = 1000 * 3.1622776601683795
      = 3162.2776601683795``  (``1000 ** (1/6) == 10 ** 0.5``)
    * numerator ``= 0.74183 * 3162.2776601683795 = 2345.8317...``
    * inner ``= 0.025574 * 1000 + 0.021433 * 2**3
      = 25.574 + 0.171464 = 25.745464``
    * ``sqrt(25.745464) = 5.0739988...``
    * denominator ``= 5.0739988... * (60 - 20) = 202.9599...``
    * result ``= 11.558302046462384``

    The final value is frozen as a literal so this test compares against
    a hand-carried number rather than re-running the implementation's
    own expression.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_scorch_ht(1000.0, 20.0, 2.0)), 11.558302046462384)


@pytest.mark.parametrize(("sfi", "cube_power"), sorted(_EXACT_CUBE_INTENSITIES.items()))
def test_scorch_ht_equation_8_hand_derived_values(sfi, cube_power):
    """
    Equation 8 (no ambient temperature) must evaluate
    ``0.1483 * I ** (2/3)``.

    :param sfi: Surface fire intensity (kW/m).
    :param cube_power: The exact integer value of ``sfi ** (2/3)``.
    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_scorch_ht(sfi)), 0.1483 * cube_power)


def test_scorch_ht_equation_8_selected_whenever_amb_t_is_none():
    """
    Mode selection is driven by ``amb_t`` alone: supplying
    ``instand_ws`` without ``amb_t`` still selects equation 8, so the
    windspeed argument is silently ignored.

    Pinned because it is a real, undocumented API trap - a caller who
    passes only a windspeed gets the no-wind equation with no warning.

    :return: None. Raises via ``assert`` on mismatch.
    """
    with_wind = float(calc_scorch_ht(1000.0, None, 3.0))
    without_wind = float(calc_scorch_ht(1000.0))
    _assert_close(with_wind, without_wind)
    _assert_close(with_wind, 0.1483 * 100.0)


@pytest.mark.parametrize(
    ("sfi", "amb_t", "expected"),
    [
        # 4.4713 * I**(2/3) / (60 - amb_t), using the exact-cube powers.
        (1000.0, 20.0, 4.4713 * 100.0 / 40.0),      # = 11.178250
        (8000.0, 10.0, 4.4713 * 400.0 / 50.0),      # = 35.770400
        (27000.0, 35.0, 4.4713 * 900.0 / 25.0),     # = 160.966800
        (125.0, 0.0, 4.4713 * 25.0 / 60.0),         # =  1.863042
    ],
)
def test_scorch_ht_equation_9_hand_derived_values(sfi, amb_t, expected):
    """
    Equation 9 (``amb_t`` supplied, ``instand_ws`` omitted) must evaluate
    ``4.4713 * I ** (2/3) / (60 - amb_t)``.

    Every case uses an intensity whose two-thirds power is an exact
    integer (see :data:`_EXACT_CUBE_INTENSITIES`), so the expected value
    is a product of three exactly representable factors written out in
    the parametrisation rather than a re-execution of the
    implementation.

    :param sfi: Surface fire intensity (kW/m).
    :param amb_t: Ambient temperature (C).
    :param expected: Hand-derived scorch height (m).
    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_scorch_ht(sfi, amb_t)), expected)


@pytest.mark.parametrize("bad_input", [None, [None], [1.0, None]])
def test_scorch_ht_missing_intensity_guard_fires_for_object_dtype(bad_input):
    """
    The ``np.any(sfi == None)`` guard **does** fire for object-dtype
    inputs, contrary to a blanket "dead code" reading of Gate 0 finding
    **F-24**.

    ``np.asarray(None)`` and ``np.asarray([1.0, None])`` both produce
    object-dtype arrays, and NumPy compares object arrays against
    ``None`` element by element, so the guard raises exactly as intended
    for a genuinely missing intensity. F-24's precise claim - that the
    comparison "is never true for a numeric array" - is confirmed by the
    companion test below; the broader claim that the guard is dead code
    is not. See this module's docstring and the Phase 3 findings.

    :param bad_input: An input that produces an object-dtype array.
    :return: None. Raises via ``assert`` on mismatch.
    """
    with pytest.raises(Exception, match="Must enter a surface fire intensity"):
        calc_scorch_ht(bad_input)


def test_scorch_ht_missing_intensity_guard_is_inert_for_numeric_nan():
    """
    The same guard is inert for a float-dtype array: a NaN intensity is
    not caught and propagates through the equation, which is the half of
    Gate 0 finding **F-24** that is accurate as written.

    :return: None. Raises via ``assert`` on mismatch.
    """
    result = calc_scorch_ht(np.array([np.nan, 1000.0]))
    assert np.isnan(result[0])
    _assert_close(float(result[1]), 0.1483 * 100.0)


def test_scorch_ht_negative_intensity_returns_nan():
    """
    A negative fire intensity raised to a fractional power yields NaN
    with a NumPy ``RuntimeWarning``; the function performs no domain
    validation on ``sfi``.

    :return: None. Raises via ``assert`` on mismatch.
    """
    with pytest.warns(RuntimeWarning, match="invalid value"):
        result = calc_scorch_ht(-5.0)
    assert np.isnan(result)


def test_scorch_ht_scalar_matches_length_one_array():
    """
    A scalar call and a length-one array call must agree, for all three
    equations.

    :return: None. Raises via ``assert`` on mismatch.
    """
    cases = ((1000.0,), (1000.0, 20.0), (1000.0, 20.0, 2.0))
    for args in cases:
        scalar = float(calc_scorch_ht(*args))
        arrayed = calc_scorch_ht(np.array([args[0]]), *args[1:])
        assert arrayed.shape == (1,)
        _assert_close(float(arrayed[0]), scalar)


def test_scorch_ht_zero_intensity_is_zero():
    """
    Zero fire intensity yields zero scorch height in equations 8 and 9.

    Equation 10 is excluded: at ``sfi == 0`` and ``ws == 0`` its
    denominator is also zero, which is a separate degenerate case not
    claimed by this test.

    :return: None. Raises via ``assert`` on mismatch.
    """
    _assert_close(float(calc_scorch_ht(0.0)), 0.0)
    _assert_close(float(calc_scorch_ht(0.0, 20.0)), 0.0)
