#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
test_phase5_soil_campbell_contract.py - Phase 5 Python-side coverage for
``soil_heat_campbell`` (``src/pyfofem/components/soil_heating.py``).

**Assertion classes (required module declaration):**

- Class **(a) Python contract tests** - nominal behaviour, ``duff``/
  ``non_duff`` model routing, input validation/boundaries, output
  DataFrame structure (index/columns/units/finiteness), repeatability, and
  oracle-independent physical invariants (e.g. a zero fire-intensity
  series must not raise the soil above its starting temperature). These
  make no C++ parity claim.
- Class **(b) source-relation checks** - ``test_*_source_relation`` below,
  which compare Python constants against values hand-transcribed from the
  pinned C++ source with the ``file:line`` cited in each docstring. NOT
  executable parity.
- Class **(c) manifested executable C++ parity - NOT PRESENT in this
  module, by design.** See the note below and the companion module.

**Why no class (c) tests here, and where they actually live (F-17 / F-51 /
F-52).** The Phase 5 golden dataset
(``tests/test_data/test_golden_output/phase5/soil_campbell/``, generated by
``tests/cpp_parity_live/generate_phase5_goldens.py``) exists and is real,
manifested, and verified deterministic, and real Python-vs-C++ numeric
comparisons DO exist — in the sibling module
``test_phase5_soil_campbell_characterization.py`` — but they are explicitly
**cross-implementation characterization, not parity**: F-52
(``gate0/04-findings.md``) measured that Python's ``soil_heat_campbell()``
and C++'s ``soiltemp_step`` are structurally different models (C++
integrates coupled moisture/vapor/latent-heat state and an ambient
radiative floor absent from Python), not one model at two numerical
precisions or one model with a mismatched constant table — a 16-49 degC
divergence persists even after aligning every Python-consumed soil-property
input to the pinned C++ table, for every family including
``"coarse-silty"``/C++ ``Coarse-Silt`` (F-51's one matching family). Every
``soil_campbell_p5`` route in ``tolerance_policy.json`` therefore stays
honestly ``"status": "unverified"``/``"contract_only"`` (real null
``atol``/``rtol``) — no measured divergence, however documented, is
converted into a tolerance bound. This module keeps to classes (a)/(b)
only, deliberately, so a reader does not mistake either kind of test for a
parity claim.

Also documents one real Python/C++ CONTRACT difference discovered while
building this module, independent of any numeric divergence:
``soil_heat_campbell``'s ``model`` parameter is an explicit caller choice
(``"duff"``/``"non_duff"``); C++'s ``SH_Mngr`` instead INFERS the route
from whether ``duff_dep_pre_in > 0`` (harness-contract section 7). Neither
side is wrong - they are simply different points in the same pipeline
(Python expects the caller to have already decided which surface-flux
model applies; C++ decides it internally from a duff-depth input Python's
function does not take at all) - but a caller porting scenarios between
the two schemas must make that routing decision explicitly, since Python
has no ``duff_dep_pre_in``-equivalent auto-selection.

Function order: private helpers first, then public test functions, each
group alphabetized, per AGENTS.md.
"""
from __future__ import annotations

import inspect

import numpy as np
import pandas as pd
import pytest

from pyfofem.components.soil_heating import _SOIL_FAMILY_DEFAULTS, soil_heat_campbell

pytestmark = pytest.mark.soil_solver

#: 13 depths (cm), matching the Phase 5 BR-SOI-DUFF/NODUFF scenario
#: matrix's use of the C++ eC_Lay==14 (Surface + 13 layers) convention.
_DEPTHS = list(range(1, 14))

#: A short, clearly-decaying fire-intensity series (mirrors
#: ``_phase5_contract.py``'s shared side-file formula so the same physical
#: scenario shape is exercised on both sides of the port, even though no
#: numeric comparison is attempted yet - see the module docstring).
_N_STEPS = 20
_TIMES_S = [i * 15.0 for i in range(_N_STEPS)]
_WL_SERIES = [max(0.0, 50.0 - 3.0 * i) for i in range(_N_STEPS)]
_HS_SERIES = [max(0.0, 10.0 - 0.5 * i) for i in range(_N_STEPS)]


def _duff_params(**overrides) -> dict:
    """
    Build a valid ``duff_params`` dict for :func:`soil_heat_campbell`'s
    ``model="duff"`` path, with optional field overrides.

    :param overrides: Fields to override in the base dict.
    :returns: A ``duff_params`` dict.
    """
    base = dict(duff_load=5.0, duff_depth=2.0, duff_moisture=60.0, pct_consumed=50.0)
    base.update(overrides)
    return base


def _soil_params(soil_family: str = "coarse-silty", start_water: float = 0.10,
                  start_temp: float = 21.0, **overrides) -> dict:
    """
    Build a valid ``soil_params`` dict for :func:`soil_heat_campbell`, with
    optional field overrides.

    ``"coarse-silty"`` is the default because it is the one soil family
    F-51 confirms has C++-matching physical constants - the most credible
    target for any future class (c) comparison built on top of this
    module's fixtures.

    :param soil_family: One of :data:`_SOIL_FAMILY_DEFAULTS`'s keys.
    :param start_water: Starting volumetric water content (m3/m3).
    :param start_temp: Starting soil temperature (degC).
    :param overrides: Additional fields to override in the base dict.
    :returns: A ``soil_params`` dict.
    """
    base = dict(soil_family=soil_family, start_water=start_water, start_temp=start_temp)
    base.update(overrides)
    return base


def test_duff_route_produces_finite_dataframe():
    """Class (a). The ``model="duff"`` path must return a fully finite
    DataFrame (no NaN/Inf) - a solver instability would otherwise surface
    only as a silent downstream NaN."""
    df = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    assert np.isfinite(df.to_numpy()).all()


def test_duff_vs_non_duff_are_explicit_caller_choices_not_auto_routed():
    """Class (a) contract note. Unlike C++'s SH_Mngr (which infers the
    route from duff_dep_pre_in > 0), soil_heat_campbell has no field that
    silently changes which model runs - passing "duff" always takes the
    duff-flux path and "non_duff" always takes the burnup-intensity path,
    regardless of what duff_params/burnup_* values happen to be set to."""
    duff_df = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    non_duff_df = soil_heat_campbell(
        "non_duff", {}, _soil_params(), _DEPTHS,
        burnup_intensity=_WL_SERIES, burnup_intensity_hs=_HS_SERIES,
        burnup_times=_TIMES_S,
    )
    # Both routes are independently well-formed and are not required to
    # agree with each other - they model physically different surface
    # fluxes. The contract being tested is that each stays on its own path.
    assert list(duff_df.columns) == list(non_duff_df.columns)
    assert duff_df.index.name == non_duff_df.index.name == "time_min"


def test_invalid_model_raises_value_error():
    """Class (a). An unrecognised ``model`` string must raise, not
    silently default to one route."""
    with pytest.raises(ValueError, match="model must be"):
        soil_heat_campbell("bogus", {}, _soil_params(), _DEPTHS)


def test_invalid_soil_family_raises_value_error():
    """Class (a). ``soil_params['soil_family']`` must be one of the five
    recognised families - a typo must raise, not silently fall back to a
    default family's constants."""
    with pytest.raises(ValueError, match="Unrecognised soil_family"):
        soil_heat_campbell(
            "duff", _duff_params(), _soil_params(soil_family="not-a-family"),
            _DEPTHS,
        )


def test_non_duff_route_produces_finite_dataframe():
    """Class (a). The ``model="non_duff"`` path must return a fully finite
    DataFrame."""
    df = soil_heat_campbell(
        "non_duff", {}, _soil_params(), _DEPTHS,
        burnup_intensity=_WL_SERIES, burnup_intensity_hs=_HS_SERIES,
        burnup_times=_TIMES_S,
    )
    assert np.isfinite(df.to_numpy()).all()


def test_output_columns_and_index_contract():
    """Class (a). Column order must be ``['Surface', '<d>cm', ...]`` in
    *depth_layers* order, and the index must be named ``'time_min'``,
    start at 0, and be strictly non-decreasing."""
    depths = [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
    df = soil_heat_campbell("duff", _duff_params(), _soil_params(), depths)
    assert list(df.columns) == ["Surface"] + [f"{d}cm" for d in depths]
    assert df.index.name == "time_min"
    assert df.index[0] == pytest.approx(0.0)
    assert df.index.is_monotonic_increasing


def test_output_starts_at_start_temp():
    """Class (a). Every column's value at ``time_min == 0`` must equal
    ``soil_params['start_temp']`` exactly - the ODE's own initial
    condition, not a solver artifact."""
    df = soil_heat_campbell(
        "duff", _duff_params(), _soil_params(start_temp=17.5), _DEPTHS,
    )
    first_row = df.iloc[0].to_numpy()
    assert first_row == pytest.approx(17.5)


def test_repeated_calls_are_deterministic():
    """Class (a). Two identical calls must produce identical output - no
    hidden global/random state (mirrors the C++ harness's own row15/row16
    determinism self-tests for soil_campbell)."""
    df_a = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    df_b = soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS)
    pd.testing.assert_frame_equal(df_a, df_b)


def test_soil_family_defaults_source_relation():
    """Class (b). Pins F-51's measured evidence as an executable
    regression: Python's ``_SOIL_FAMILY_DEFAULTS`` must continue to match
    the pinned C++ ``sr_SE``/``sr_SD`` table
    (``reference/fofem_cpp/FOF_UNIX/fof_se2.h:11-20``,
    ``fof_sd2.h:8-21``; both tables carry identical per-family values) for
    ``"coarse-silty"`` (the one family F-51 found matching), and must NOT
    silently start matching for the other four (F-51's whole point is that
    they currently do not - if a future edit makes them match, F-51's
    'only Coarse-Silt' claim needs updating right alongside this test, not
    a bare test failure)."""
    coarse_silty = _SOIL_FAMILY_DEFAULTS["coarse-silty"]
    # C++ Coarse-Silt row (fof_se2.h:53-64 / fof_sd2.h; g/m3 -> kg/m3 by /1000).
    assert coarse_silty["bulk_density"] == pytest.approx(1230.0)
    assert coarse_silty["particle_density"] == pytest.approx(2350.0)
    assert coarse_silty["k_mineral"] == pytest.approx(2.53)
    assert coarse_silty["vries_shape"] == pytest.approx(0.103)
    assert coarse_silty["cop_power"] == pytest.approx(3.43)
    # extrap_water is the one field that does NOT match exactly even for
    # Coarse-Silt (0.157 C++ vs 0.16 Python, 1.9% - F-51's table).
    assert coarse_silty["extrap_water"] == pytest.approx(0.157, rel=0.02)

    fine_silty = _SOIL_FAMILY_DEFAULTS["fine-silty"]
    # C++ Fine-Silt row (fof_se2.h:13-23): bulk_density=1300 kg/m3,
    # k_mineral=2.31. Python's fine-silty is a DIFFERENT soil (F-51) -
    # asserting the two do NOT match pins that finding.
    assert fine_silty["bulk_density"] != pytest.approx(1300.0, rel=0.01)
    assert fine_silty["k_mineral"] != pytest.approx(2.31, rel=0.01)


def test_wl_hs_efficiency_defaults_source_relation():
    """Class (b). ``efficiency_wl=0.15``/``efficiency_hs=0.10`` (function
    defaults) match C++'s own "use built-in default" fallback exactly:
    ``fof_se.cpp:64-67`` sets ``f_SoilWlEff=0.15``/``f_SoilHsEff=0.10``
    whenever the input percent is negative (the harness's own ``-1``
    sentinel convention), after converting the raw whole-number-percent
    input to a decimal fraction (``fof_se.cpp:62-63``, ``/100.0``) - the
    same units Python's parameters are already in."""
    sig = inspect.signature(soil_heat_campbell)
    assert sig.parameters["efficiency_wl"].default == pytest.approx(0.15)
    assert sig.parameters["efficiency_hs"].default == pytest.approx(0.10)


def test_wrong_depth_layers_length_raises_value_error():
    """Class (a). *depth_layers* must contain exactly 13 values (matching
    C++'s fixed ``eC_Lay==14`` Surface+13-layer convention) - too few or
    too many must raise, never silently truncate/pad."""
    with pytest.raises(ValueError, match="exactly 13 values"):
        soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS[:-1])
    with pytest.raises(ValueError, match="exactly 13 values"):
        soil_heat_campbell("duff", _duff_params(), _soil_params(), _DEPTHS + [14])


def test_zero_fire_intensity_never_exceeds_start_temp():
    """Class (a), oracle-independent physical invariant. A non_duff run
    with an all-zero fire-intensity series delivers zero surface flux, so
    the soil column must never exceed its own starting temperature (up to
    solver tolerance) - true regardless of which side (Python or C++, or
    neither) is scientifically "correct", since it follows from energy
    conservation alone, not from matching any oracle."""
    df = soil_heat_campbell(
        "non_duff", {}, _soil_params(start_temp=15.0), _DEPTHS,
        burnup_intensity=[0.0] * _N_STEPS, burnup_intensity_hs=[0.0] * _N_STEPS,
        burnup_times=_TIMES_S,
    )
    assert (df.to_numpy() <= 15.0 + 1e-6).all()
